"""sync database with models (TEMPLATE)

Revision ID: 041
Revises: 040
Create Date: 2024-01-20 05:00:00.000000

This is a TEMPLATE showing best practices for autogenerated migrations.
Copy and adapt this template when creating new autogenerated migrations.

MySQL COMPATIBILITY NOTES:
==========================
This template is designed for MySQL compatibility. Key differences from PostgreSQL:

1. NO ROW LEVEL SECURITY (RLS): MySQL does not support RLS policies.
   Use application-level filtering or views with DEFINER for isolation.

2. NO NATIVE UUID TYPE: Use CHAR(36) or BINARY(16) for UUIDs.
   Generate UUIDs in application code, not database.

3. JSON vs JSONB: MySQL only supports JSON (no JSONB).
   JSON validation and indexing available via virtual columns.

4. ENUM HANDLING: MySQL has native ENUM type but it's limited.
   Consider using VARCHAR with CHECK constraints for better flexibility.
   ENUMs cannot be easily altered (requires table rebuild).

5. TIMESTAMPS: Use DATETIME or TIMESTAMP.
   DATETIME is timezone-naive, TIMESTAMP has timezone conversion.
   Default: CURRENT_TIMESTAMP (not now())

6. BOOLEAN TYPE: MySQL converts BOOLEAN to TINYINT(1).
   Values: 0 (false), 1 (true).

Best Practices Demonstrated:
1. Existence checks before creating objects
2. Idempotent operations
3. Safe handling of enum types
4. Proper error handling
5. Data preservation during schema changes
6. Clear documentation
7. MySQL-specific information_schema queries
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '041'
down_revision = '040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply schema changes to sync database with models.
    
    This upgrade function demonstrates:
    - Safe table creation with existence checks
    - Safe enum creation with existence checks (MySQL native ENUM)
    - Safe column additions
    - Safe constraint additions
    - Safe index creation
    
    MySQL-specific considerations:
    - Uses information_schema for existence checks
    - No RLS support (handled at application level)
    - ENUM limitations (prefer VARCHAR with constraints for flexibility)
    - No native UUID type (use CHAR(36) or BINARY(16))
    """
    # Get database connection for existence checks
    conn = op.get_bind()
    
    # Get current database name
    db_name = conn.execute(sa.text("SELECT DATABASE()")).scalar()
    
    # ========================================================================
    # ENUM TYPE CREATION (MySQL native ENUM in column definition)
    # ========================================================================
    
    # NOTE: MySQL ENUMs are defined in column definition, not as separate types
    # If you need to change ENUM values later, consider using VARCHAR with CHECK constraint
    # 
    # Example of CHECK constraint approach (more flexible):
    # sa.Column('status', sa.String(length=20), nullable=False),
    # sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", 
    #                    name='ck_example_table_status')
    #
    # For MySQL native ENUM (less flexible, requires table rebuild to alter):
    # sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='statusenum'),
    #           nullable=False, server_default='pending')
    
    # ========================================================================
    # TABLE CREATION (with existence checks)
    # ========================================================================
    
    # Example: Create table only if it doesn't exist
    table_name = 'example_table'
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = :db_name 
            AND table_name = :table_name
        """),
        {"db_name": db_name, "table_name": table_name}
    ).scalar()
    
    if result == 0:
        op.create_table(
            'example_table',
            sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
            sa.Column('institution_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            # MySQL ENUM approach (native):
            sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='statusenum'), 
                      nullable=False, server_default='pending'),
            # Alternative: VARCHAR with CHECK constraint (more flexible):
            # sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
            sa.Column('count', sa.Integer(), nullable=False, server_default='0'),
            # MySQL timestamp defaults: CURRENT_TIMESTAMP
            sa.Column('created_at', sa.DateTime(), nullable=False, 
                      server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('updated_at', sa.DateTime(), nullable=True,
                      server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], 
                                   ondelete='CASCADE'),
        )
        print(f"Created table: {table_name}")
        
        # Create indexes for the new table
        op.create_index(
            'ix_example_table_institution_id', 
            'example_table', 
            ['institution_id']
        )
        op.create_index(
            'ix_example_table_status', 
            'example_table', 
            ['status']
        )
    else:
        print(f"Table already exists: {table_name}")
    
    # ========================================================================
    # COLUMN ADDITION (with existence checks)
    # ========================================================================
    
    # Example: Add column only if it doesn't exist
    table_to_modify = 'existing_table'
    column_to_add = 'new_column'
    
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.columns 
            WHERE table_schema = :db_name 
            AND table_name = :table_name 
            AND column_name = :column_name
        """),
        {"db_name": db_name, "table_name": table_to_modify, "column_name": column_to_add}
    ).scalar()
    
    if result == 0:
        # Check if table exists first
        table_exists = conn.execute(
            sa.text(f"""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = :db_name 
                AND table_name = :table_name
            """),
            {"db_name": db_name, "table_name": table_to_modify}
        ).scalar()
        
        if table_exists > 0:
            op.add_column(
                table_to_modify,
                sa.Column(column_to_add, sa.String(length=100), nullable=True)
            )
            print(f"Added column: {table_to_modify}.{column_to_add}")
        else:
            print(f"Table does not exist: {table_to_modify}")
    else:
        print(f"Column already exists: {table_to_modify}.{column_to_add}")
    
    # ========================================================================
    # UUID COLUMN HANDLING (MySQL has no native UUID type)
    # ========================================================================
    
    # Example: Add UUID column (use CHAR(36) for string format or BINARY(16) for binary)
    # Generate UUIDs in application code, not in database
    
    # Option 1: CHAR(36) - human-readable, easier to debug
    # sa.Column('uuid', sa.CHAR(36), nullable=False, unique=True)
    #
    # Option 2: BINARY(16) - more efficient storage
    # sa.Column('uuid', sa.LargeBinary(16), nullable=False, unique=True)
    # In application: uuid.uuid4().bytes to store, uuid.UUID(bytes=...) to retrieve
    
    # ========================================================================
    # JSON COLUMN HANDLING (MySQL: JSON, not JSONB)
    # ========================================================================
    
    # Example: Add JSON column
    # MySQL validates JSON on insert/update
    # sa.Column('metadata', sa.JSON(), nullable=True)
    #
    # For indexing JSON fields, use generated/virtual columns:
    # ALTER TABLE example_table 
    # ADD COLUMN metadata_type VARCHAR(50) AS (metadata->>'$.type') STORED;
    # CREATE INDEX ix_metadata_type ON example_table(metadata_type);
    
    # ========================================================================
    # FOREIGN KEY ADDITION (with existence checks)
    # ========================================================================
    
    # Example: Add foreign key only if it doesn't exist
    fk_constraint_name = 'fk_example_table_parent_id'
    
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_schema = :db_name 
            AND constraint_name = :constraint_name
            AND constraint_type = 'FOREIGN KEY'
        """),
        {"db_name": db_name, "constraint_name": fk_constraint_name}
    ).scalar()
    
    if result == 0:
        op.create_foreign_key(
            fk_constraint_name,
            'example_table',
            'parent_table',
            ['parent_id'],
            ['id'],
            ondelete='CASCADE'
        )
        print(f"Created foreign key: {fk_constraint_name}")
    else:
        print(f"Foreign key already exists: {fk_constraint_name}")
    
    # ========================================================================
    # INDEX CREATION (with existence checks)
    # ========================================================================
    
    # Example: Create index only if it doesn't exist
    index_name = 'ix_example_table_composite'
    
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.statistics 
            WHERE table_schema = :db_name 
            AND index_name = :index_name
        """),
        {"db_name": db_name, "index_name": index_name}
    ).scalar()
    
    if result == 0:
        op.create_index(
            index_name,
            'example_table',
            ['institution_id', 'status']
        )
        print(f"Created index: {index_name}")
    else:
        print(f"Index already exists: {index_name}")
    
    # ========================================================================
    # UNIQUE CONSTRAINT ADDITION (with existence checks)
    # ========================================================================
    
    # Example: Add unique constraint only if it doesn't exist
    unique_constraint_name = 'uq_example_table_name_institution'
    
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_schema = :db_name 
            AND constraint_name = :constraint_name
            AND constraint_type = 'UNIQUE'
        """),
        {"db_name": db_name, "constraint_name": unique_constraint_name}
    ).scalar()
    
    if result == 0:
        # Check for duplicate data first
        duplicates = conn.execute(
            sa.text(f"""
                SELECT institution_id, name, COUNT(*) as cnt
                FROM example_table 
                GROUP BY institution_id, name 
                HAVING COUNT(*) > 1
            """)
        ).fetchall()
        
        if duplicates:
            print(f"WARNING: Found {len(duplicates)} duplicate records in example_table")
            print(f"Clean up duplicates before adding unique constraint")
        else:
            op.create_unique_constraint(
                unique_constraint_name,
                'example_table',
                ['institution_id', 'name']
            )
            print(f"Created unique constraint: {unique_constraint_name}")
    else:
        print(f"Unique constraint already exists: {unique_constraint_name}")
    
    # ========================================================================
    # CHECK CONSTRAINT ADDITION (for ENUM-like behavior)
    # ========================================================================
    
    # Example: Add CHECK constraint (MySQL 8.0.16+)
    # More flexible than ENUM type - can be modified without table rebuild
    
    check_constraint_name = 'ck_example_table_status'
    
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_schema = :db_name 
            AND constraint_name = :constraint_name
            AND constraint_type = 'CHECK'
        """),
        {"db_name": db_name, "constraint_name": check_constraint_name}
    ).scalar()
    
    # Uncomment if using VARCHAR + CHECK constraint instead of ENUM:
    # if result == 0:
    #     op.create_check_constraint(
    #         check_constraint_name,
    #         'example_table',
    #         "status IN ('pending', 'approved', 'rejected')"
    #     )
    #     print(f"Created check constraint: {check_constraint_name}")
    # else:
    #     print(f"Check constraint already exists: {check_constraint_name}")
    
    # ========================================================================
    # ALTER COLUMN (with safety checks)
    # ========================================================================
    
    # Example: Safely alter column to NOT NULL
    table_for_alter = 'example_table'
    column_for_alter = 'status'
    
    # Check if column has NULL values
    null_count = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) FROM {table_for_alter} 
            WHERE {column_for_alter} IS NULL
        """)
    ).scalar()
    
    if null_count == 0:
        # Check current nullable status
        result = conn.execute(
            sa.text(f"""
                SELECT is_nullable 
                FROM information_schema.columns 
                WHERE table_schema = :db_name 
                AND table_name = :table_name 
                AND column_name = :column_name
            """),
            {"db_name": db_name, "table_name": table_for_alter, "column_name": column_for_alter}
        ).scalar()
        
        if result == 'YES':
            # MySQL requires full column definition in ALTER
            # Get current column type
            col_info = conn.execute(
                sa.text(f"""
                    SELECT column_type, column_default 
                    FROM information_schema.columns 
                    WHERE table_schema = :db_name 
                    AND table_name = :table_name 
                    AND column_name = :column_name
                """),
                {"db_name": db_name, "table_name": table_for_alter, "column_name": column_for_alter}
            ).fetchone()
            
            # Note: For complex alterations, use op.alter_column()
            # which handles the MySQL-specific syntax
            op.alter_column(
                table_for_alter,
                column_for_alter,
                nullable=False,
                existing_type=sa.String(),  # Adjust based on actual column type
            )
            print(f"Set NOT NULL on: {table_for_alter}.{column_for_alter}")
        else:
            print(f"Column already NOT NULL: {table_for_alter}.{column_for_alter}")
    else:
        print(f"WARNING: {null_count} NULL values in {table_for_alter}.{column_for_alter}")
        print(f"Cannot set NOT NULL - fix data first")
    
    # ========================================================================
    # ROW LEVEL SECURITY (RLS) - NOT SUPPORTED IN MYSQL
    # ========================================================================
    
    # WARNING: MySQL does NOT support Row Level Security (RLS) like PostgreSQL
    #
    # Alternative approaches for multi-tenant isolation in MySQL:
    #
    # 1. Application-level filtering (RECOMMENDED):
    #    Always include WHERE institution_id = :current_institution_id in queries
    #
    # 2. Database views with security definer:
    #    CREATE DEFINER='app_user'@'localhost' SQL SECURITY DEFINER VIEW ...
    #
    # 3. Triggers for validation:
    #    CREATE TRIGGER before_insert_example_table ...
    #
    # 4. Stored procedures with DEFINER:
    #    All data access through stored procedures that enforce isolation
    #
    # Example application-level pattern:
    # 
    # from sqlalchemy.orm import Session
    # from sqlalchemy import event
    # 
    # @event.listens_for(Session, "after_attach")
    # def receive_after_attach(session, instance):
    #     # Automatically filter queries by institution_id
    #     if hasattr(instance, 'institution_id'):
    #         # Validate institution_id matches current user's institution
    #         pass
    
    # ========================================================================
    # DATA MIGRATION (if needed)
    # ========================================================================
    
    # Example: Populate default values for existing rows
    # This is needed when adding NOT NULL columns to existing tables
    
    # Uncomment and modify as needed:
    # op.execute("""
    #     UPDATE example_table 
    #     SET new_column = 'default_value' 
    #     WHERE new_column IS NULL
    # """)
    
    # Example: Migrate JSONB to JSON (when migrating from PostgreSQL)
    # MySQL JSON syntax uses -> and ->> operators similar to PostgreSQL
    # However, functions may differ:
    # PostgreSQL: jsonb_path_query()
    # MySQL: JSON_EXTRACT(), JSON_UNQUOTE()
    
    # Example: Migrate UUID to CHAR(36) or BINARY(16)
    # If migrating from PostgreSQL UUID type:
    # op.execute("""
    #     UPDATE example_table 
    #     SET uuid_char = LOWER(CONCAT(
    #         SUBSTR(HEX(uuid_binary), 1, 8), '-',
    #         SUBSTR(HEX(uuid_binary), 9, 4), '-',
    #         SUBSTR(HEX(uuid_binary), 13, 4), '-',
    #         SUBSTR(HEX(uuid_binary), 17, 4), '-',
    #         SUBSTR(HEX(uuid_binary), 21)
    #     ))
    # """)
    
    print("\n✓ Upgrade completed successfully")


def downgrade() -> None:
    """
    Rollback schema changes.
    
    Note: Downgrade functions should be written carefully to:
    - Preserve data where possible
    - Clearly document any data loss
    - Be tested thoroughly
    
    MySQL considerations:
    - Use information_schema for existence checks
    - CHECK constraints require MySQL 8.0.16+
    - ENUM alterations may require table rebuild
    """
    conn = op.get_bind()
    
    # Get current database name
    db_name = conn.execute(sa.text("SELECT DATABASE()")).scalar()
    
    # ========================================================================
    # NOTE: No RLS to drop in MySQL
    # ========================================================================
    
    # Drop unique constraints
    unique_constraint_name = 'uq_example_table_name_institution'
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_schema = :db_name 
            AND constraint_name = :constraint_name
            AND constraint_type = 'UNIQUE'
        """),
        {"db_name": db_name, "constraint_name": unique_constraint_name}
    ).scalar()
    
    if result > 0:
        op.drop_constraint(unique_constraint_name, 'example_table', type_='unique')
        print(f"Dropped unique constraint: {unique_constraint_name}")
    
    # Drop check constraints (if used)
    check_constraint_name = 'ck_example_table_status'
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_schema = :db_name 
            AND constraint_name = :constraint_name
            AND constraint_type = 'CHECK'
        """),
        {"db_name": db_name, "constraint_name": check_constraint_name}
    ).scalar()
    
    if result > 0:
        op.drop_constraint(check_constraint_name, 'example_table', type_='check')
        print(f"Dropped check constraint: {check_constraint_name}")
    
    # Drop indexes
    indexes_to_drop = [
        'ix_example_table_composite',
        'ix_example_table_status',
        'ix_example_table_institution_id',
    ]
    
    for index_name in indexes_to_drop:
        result = conn.execute(
            sa.text(f"""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = :db_name 
                AND index_name = :index_name
            """),
            {"db_name": db_name, "index_name": index_name}
        ).scalar()
        
        if result > 0:
            op.drop_index(index_name, table_name='example_table')
            print(f"Dropped index: {index_name}")
    
    # Drop foreign keys
    fk_constraint_name = 'fk_example_table_parent_id'
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_schema = :db_name 
            AND constraint_name = :constraint_name
            AND constraint_type = 'FOREIGN KEY'
        """),
        {"db_name": db_name, "constraint_name": fk_constraint_name}
    ).scalar()
    
    if result > 0:
        op.drop_constraint(fk_constraint_name, 'example_table', type_='foreignkey')
        print(f"Dropped foreign key: {fk_constraint_name}")
    
    # Drop columns (WARNING: This will lose data!)
    column_to_drop = 'new_column'
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.columns 
            WHERE table_schema = :db_name 
            AND table_name = :table_name 
            AND column_name = :column_name
        """),
        {"db_name": db_name, "table_name": 'existing_table', "column_name": column_to_drop}
    ).scalar()
    
    if result > 0:
        print(f"WARNING: Dropping column will lose data: existing_table.{column_to_drop}")
        op.drop_column('existing_table', column_to_drop)
        print(f"Dropped column: existing_table.{column_to_drop}")
    
    # Drop tables (WARNING: This will lose data!)
    table_to_drop = 'example_table'
    result = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = :db_name 
            AND table_name = :table_name
        """),
        {"db_name": db_name, "table_name": table_to_drop}
    ).scalar()
    
    if result > 0:
        print(f"WARNING: Dropping table will lose data: {table_to_drop}")
        op.drop_table(table_to_drop)
        print(f"Dropped table: {table_to_drop}")
    
    # NOTE: MySQL ENUMs are dropped automatically when the table/column is dropped
    # No separate type to drop like in PostgreSQL
    
    print("\n✓ Downgrade completed successfully")
