"""sync database with models (TEMPLATE)

Revision ID: 041
Revises: 040
Create Date: 2024-01-20 05:00:00.000000

This is a TEMPLATE showing best practices for autogenerated migrations.
Copy and adapt this template when creating new autogenerated migrations.

Best Practices Demonstrated:
1. Existence checks before creating objects
2. Idempotent operations
3. Safe handling of enum types
4. Proper error handling
5. Data preservation during schema changes
6. Clear documentation
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '041'
down_revision = '040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply schema changes to sync database with models.
    
    This upgrade function demonstrates:
    - Safe table creation with existence checks
    - Safe enum creation with existence checks
    - Safe column additions
    - Safe constraint additions
    - Safe index creation
    """
    # Get database connection for existence checks
    conn = op.get_bind()
    
    # ========================================================================
    # ENUM TYPE CREATION (with existence checks)
    # ========================================================================
    
    # Example: Create enum type only if it doesn't exist
    enum_types_to_create = [
        ('exampleenum', "('value1', 'value2', 'value3')"),
        ('statusenum', "('pending', 'approved', 'rejected')"),
    ]
    
    for enum_name, enum_values in enum_types_to_create:
        result = conn.execute(
            sa.text(f"SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{enum_name}')")
        ).scalar()
        
        if not result:
            op.execute(f"CREATE TYPE {enum_name} AS ENUM {enum_values}")
            print(f"Created enum type: {enum_name}")
        else:
            print(f"Enum type already exists: {enum_name}")
    
    # ========================================================================
    # TABLE CREATION (with existence checks)
    # ========================================================================
    
    # Example: Create table only if it doesn't exist
    table_name = 'example_table'
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = '{table_name}'
            )
        """)
    ).scalar()
    
    if not result:
        op.create_table(
            'example_table',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('institution_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 
                                                name='statusenum', create_type=False), 
                      nullable=False, server_default='pending'),
            sa.Column('count', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('created_at', sa.DateTime(), nullable=False, 
                      server_default=sa.text('now()')),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], 
                                   ondelete='CASCADE'),
        )
        print(f"Created table: {table_name}")
        
        # Create indexes for the new table
        op.create_index(
            'ix_example_table_institution_id', 
            'example_table', 
            ['institution_id']
        )
        op.create_index(
            'ix_example_table_status', 
            'example_table', 
            ['status']
        )
    else:
        print(f"Table already exists: {table_name}")
    
    # ========================================================================
    # COLUMN ADDITION (with existence checks)
    # ========================================================================
    
    # Example: Add column only if it doesn't exist
    table_to_modify = 'existing_table'
    column_to_add = 'new_column'
    
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = '{table_to_modify}' 
                AND column_name = '{column_to_add}'
            )
        """)
    ).scalar()
    
    if not result:
        # Check if table exists first
        table_exists = conn.execute(
            sa.text(f"""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables 
                    WHERE table_name = '{table_to_modify}'
                )
            """)
        ).scalar()
        
        if table_exists:
            op.add_column(
                table_to_modify,
                sa.Column(column_to_add, sa.String(length=100), nullable=True)
            )
            print(f"Added column: {table_to_modify}.{column_to_add}")
        else:
            print(f"Table does not exist: {table_to_modify}")
    else:
        print(f"Column already exists: {table_to_modify}.{column_to_add}")
    
    # ========================================================================
    # FOREIGN KEY ADDITION (with existence checks)
    # ========================================================================
    
    # Example: Add foreign key only if it doesn't exist
    fk_constraint_name = 'fk_example_table_parent_id'
    
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = '{fk_constraint_name}'
            )
        """)
    ).scalar()
    
    if not result:
        op.create_foreign_key(
            fk_constraint_name,
            'example_table',
            'parent_table',
            ['parent_id'],
            ['id'],
            ondelete='CASCADE'
        )
        print(f"Created foreign key: {fk_constraint_name}")
    else:
        print(f"Foreign key already exists: {fk_constraint_name}")
    
    # ========================================================================
    # INDEX CREATION (with existence checks)
    # ========================================================================
    
    # Example: Create index only if it doesn't exist
    index_name = 'ix_example_table_composite'
    
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = '{index_name}'
            )
        """)
    ).scalar()
    
    if not result:
        op.create_index(
            index_name,
            'example_table',
            ['institution_id', 'status']
        )
        print(f"Created index: {index_name}")
    else:
        print(f"Index already exists: {index_name}")
    
    # ========================================================================
    # UNIQUE CONSTRAINT ADDITION (with existence checks)
    # ========================================================================
    
    # Example: Add unique constraint only if it doesn't exist
    unique_constraint_name = 'uq_example_table_name_institution'
    
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = '{unique_constraint_name}'
            )
        """)
    ).scalar()
    
    if not result:
        # Check for duplicate data first
        duplicates = conn.execute(
            sa.text(f"""
                SELECT institution_id, name, COUNT(*) 
                FROM example_table 
                GROUP BY institution_id, name 
                HAVING COUNT(*) > 1
            """)
        ).fetchall()
        
        if duplicates:
            print(f"WARNING: Found {len(duplicates)} duplicate records in example_table")
            print(f"Clean up duplicates before adding unique constraint")
        else:
            op.create_unique_constraint(
                unique_constraint_name,
                'example_table',
                ['institution_id', 'name']
            )
            print(f"Created unique constraint: {unique_constraint_name}")
    else:
        print(f"Unique constraint already exists: {unique_constraint_name}")
    
    # ========================================================================
    # ALTER COLUMN (with safety checks)
    # ========================================================================
    
    # Example: Safely alter column to NOT NULL
    table_for_alter = 'example_table'
    column_for_alter = 'status'
    
    # Check if column has NULL values
    null_count = conn.execute(
        sa.text(f"""
            SELECT COUNT(*) FROM {table_for_alter} 
            WHERE {column_for_alter} IS NULL
        """)
    ).scalar()
    
    if null_count == 0:
        # Safe to set NOT NULL
        result = conn.execute(
            sa.text(f"""
                SELECT is_nullable FROM information_schema.columns 
                WHERE table_name = '{table_for_alter}' 
                AND column_name = '{column_for_alter}'
            """)
        ).scalar()
        
        if result == 'YES':
            op.alter_column(
                table_for_alter,
                column_for_alter,
                nullable=False
            )
            print(f"Set NOT NULL on: {table_for_alter}.{column_for_alter}")
        else:
            print(f"Column already NOT NULL: {table_for_alter}.{column_for_alter}")
    else:
        print(f"WARNING: {null_count} NULL values in {table_for_alter}.{column_for_alter}")
        print(f"Cannot set NOT NULL - fix data first")
    
    # ========================================================================
    # ROW LEVEL SECURITY (RLS) POLICIES
    # ========================================================================
    
    # Example: Enable RLS and create isolation policy
    tables_for_rls = ['example_table']
    
    for table in tables_for_rls:
        # Check if table exists
        table_exists = conn.execute(
            sa.text(f"""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables 
                    WHERE table_name = '{table}'
                )
            """)
        ).scalar()
        
        if table_exists:
            # Enable RLS
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            
            # Create isolation policy
            policy_name = f"{table}_isolation_policy"
            
            # Check if policy exists
            policy_exists = conn.execute(
                sa.text(f"""
                    SELECT EXISTS (
                        SELECT 1 FROM pg_policies 
                        WHERE tablename = '{table}' 
                        AND policyname = '{policy_name}'
                    )
                """)
            ).scalar()
            
            if not policy_exists:
                op.execute(f"""
                    CREATE POLICY {policy_name} ON {table}
                    USING (
                        institution_id = current_setting('app.current_institution_id', true)::integer
                        OR current_setting('app.bypass_rls', true)::boolean = true
                    )
                """)
                print(f"Created RLS policy: {policy_name}")
            else:
                print(f"RLS policy already exists: {policy_name}")
        else:
            print(f"Table does not exist for RLS: {table}")
    
    # ========================================================================
    # DATA MIGRATION (if needed)
    # ========================================================================
    
    # Example: Populate default values for existing rows
    # This is needed when adding NOT NULL columns to existing tables
    
    # Uncomment and modify as needed:
    # op.execute("""
    #     UPDATE example_table 
    #     SET new_column = 'default_value' 
    #     WHERE new_column IS NULL
    # """)
    
    print("\n✓ Upgrade completed successfully")


def downgrade() -> None:
    """
    Rollback schema changes.
    
    Note: Downgrade functions should be written carefully to:
    - Preserve data where possible
    - Clearly document any data loss
    - Be tested thoroughly
    """
    conn = op.get_bind()
    
    # Drop RLS policies first
    tables_with_rls = ['example_table']
    for table in tables_with_rls:
        policy_name = f"{table}_isolation_policy"
        policy_exists = conn.execute(
            sa.text(f"""
                SELECT EXISTS (
                    SELECT 1 FROM pg_policies 
                    WHERE tablename = '{table}' 
                    AND policyname = '{policy_name}'
                )
            """)
        ).scalar()
        
        if policy_exists:
            op.execute(f"DROP POLICY IF EXISTS {policy_name} ON {table}")
            print(f"Dropped RLS policy: {policy_name}")
    
    # Drop unique constraints
    unique_constraint_name = 'uq_example_table_name_institution'
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = '{unique_constraint_name}'
            )
        """)
    ).scalar()
    
    if result:
        op.drop_constraint(unique_constraint_name, 'example_table', type_='unique')
        print(f"Dropped unique constraint: {unique_constraint_name}")
    
    # Drop indexes
    indexes_to_drop = [
        'ix_example_table_composite',
        'ix_example_table_status',
        'ix_example_table_institution_id',
    ]
    
    for index_name in indexes_to_drop:
        result = conn.execute(
            sa.text(f"""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = '{index_name}'
                )
            """)
        ).scalar()
        
        if result:
            op.drop_index(index_name, table_name='example_table')
            print(f"Dropped index: {index_name}")
    
    # Drop foreign keys
    fk_constraint_name = 'fk_example_table_parent_id'
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = '{fk_constraint_name}'
            )
        """)
    ).scalar()
    
    if result:
        op.drop_constraint(fk_constraint_name, 'example_table', type_='foreignkey')
        print(f"Dropped foreign key: {fk_constraint_name}")
    
    # Drop columns (WARNING: This will lose data!)
    column_to_drop = 'new_column'
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'existing_table' 
                AND column_name = '{column_to_drop}'
            )
        """)
    ).scalar()
    
    if result:
        print(f"WARNING: Dropping column will lose data: existing_table.{column_to_drop}")
        op.drop_column('existing_table', column_to_drop)
        print(f"Dropped column: existing_table.{column_to_drop}")
    
    # Drop tables (WARNING: This will lose data!)
    table_to_drop = 'example_table'
    result = conn.execute(
        sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = '{table_to_drop}'
            )
        """)
    ).scalar()
    
    if result:
        print(f"WARNING: Dropping table will lose data: {table_to_drop}")
        op.drop_table(table_to_drop)
        print(f"Dropped table: {table_to_drop}")
    
    # Drop enum types (only if no tables use them)
    enum_types_to_drop = ['exampleenum', 'statusenum']
    
    for enum_name in enum_types_to_drop:
        # Check if any columns still use this enum
        result = conn.execute(
            sa.text(f"""
                SELECT COUNT(*) FROM information_schema.columns 
                WHERE udt_name = '{enum_name}'
            """)
        ).scalar()
        
        if result == 0:
            result = conn.execute(
                sa.text(f"SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{enum_name}')")
            ).scalar()
            
            if result:
                op.execute(f"DROP TYPE IF EXISTS {enum_name}")
                print(f"Dropped enum type: {enum_name}")
        else:
            print(f"Cannot drop enum {enum_name}: still in use by {result} columns")
    
    print("\n✓ Downgrade completed successfully")
