import {
  Dashboard as DashboardIcon,
  School as SchoolIcon,
  People as PeopleIcon,
  Assignment as AssignmentIcon,
  Assessment as AssessmentIcon,
  CalendarMonth as CalendarIcon,
  Notifications as NotificationsIcon,
  Settings as SettingsIcon,
  Business as BusinessIcon,
  Person as PersonIcon,
  Class as ClassIcon,
  Book as BookIcon,
  Grade as GradeIcon,
  EmojiEvents as AchievementsIcon,
  TrendingUp as AnalyticsIcon,
  Forum as ForumIcon,
  CheckCircle as CheckCircleIcon,
  CalendarToday as CalendarTodayIcon,
  Warning as WarningIcon,
  Edit as EditIcon,
  Psychology as AIIcon,
  Flag as GoalIcon,
  Payment as PaymentIcon,
  CloudDownload as ExportIcon,
  CloudUpload as ImportIcon,
  Timer as TimerIcon,
  Store as StoreIcon,
} from '@mui/icons-material';
import { NavigationItem } from '@/types/navigation';

export const navigationConfig: NavigationItem[] = [
  {
    id: 'superadmin-dashboard',
    title: 'Dashboard',
    path: '/super-admin',
    icon: <DashboardIcon />,
    roles: ['superadmin'],
  },
  {
    id: 'superadmin-analytics',
    title: 'Analytics',
    icon: <AnalyticsIcon />,
    roles: ['superadmin'],
    children: [
      {
        id: 'superadmin-analytics-cross-institution',
        title: 'Cross-Institution Analytics',
        path: '/super-admin/analytics/cross-institution',
        icon: <AnalyticsIcon />,
      },
    ],
  },
  {
    id: 'superadmin-institutions',
    title: 'Institutions',
    icon: <BusinessIcon />,
    roles: ['superadmin'],
    children: [
      {
        id: 'superadmin-institutions-list',
        title: 'All Institutions',
        path: '/super-admin/institutions',
        icon: <BusinessIcon />,
      },
      {
        id: 'superadmin-institutions-create',
        title: 'Create Institution',
        path: '/super-admin/institutions/create',
        icon: <BusinessIcon />,
      },
    ],
  },
  {
    id: 'superadmin-settings',
    title: 'Settings',
    path: '/super-admin/settings',
    icon: <SettingsIcon />,
    roles: ['superadmin'],
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/admin',
    icon: <DashboardIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
  },
  {
    id: 'institutions',
    title: 'Institutions',
    icon: <BusinessIcon />,
    roles: ['admin', 'institution_admin'],
    children: [
      {
        id: 'institutions-list',
        title: 'All Institutions',
        path: '/admin/institutions',
        icon: <BusinessIcon />,
      },
      {
        id: 'institutions-add',
        title: 'Add Institution',
        path: '/admin/institutions/add',
        icon: <BusinessIcon />,
      },
    ],
  },
  {
    id: 'users',
    title: 'Users',
    icon: <PeopleIcon />,
    roles: ['admin', 'institution_admin'],
    children: [
      {
        id: 'users-students',
        title: 'Students',
        path: '/admin/users/students',
        icon: <PersonIcon />,
      },
      {
        id: 'users-teachers',
        title: 'Teachers',
        path: '/admin/users/teachers',
        icon: <SchoolIcon />,
      },
      {
        id: 'users-admins',
        title: 'Administrators',
        path: '/admin/users/admins',
        icon: <PeopleIcon />,
      },
    ],
  },
  {
    id: 'academic',
    title: 'Academic',
    icon: <SchoolIcon />,
    roles: ['admin', 'institution_admin', 'teacher'],
    children: [
      {
        id: 'academic-classes',
        title: 'Classes',
        path: '/admin/academic/classes',
        icon: <ClassIcon />,
      },
      {
        id: 'academic-subjects',
        title: 'Subjects',
        path: '/admin/academic/subjects',
        icon: <BookIcon />,
      },
      {
        id: 'academic-syllabus',
        title: 'Syllabus',
        path: '/admin/academic/syllabus',
        icon: <BookIcon />,
      },
    ],
  },
  {
    id: 'assignments',
    title: 'Assignments',
    path: '/admin/assignments',
    icon: <AssignmentIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
    badge: 5,
  },
  {
    id: 'examinations',
    title: 'Examinations',
    icon: <AssessmentIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
    children: [
      {
        id: 'examinations-list',
        title: 'All Exams',
        path: '/admin/examinations/list',
        icon: <AssessmentIcon />,
        roles: ['admin', 'institution_admin', 'teacher'],
      },
      {
        id: 'examinations-create',
        title: 'Create Exam',
        path: '/admin/examinations/create',
        icon: <AssessmentIcon />,
        roles: ['admin', 'institution_admin'],
      },
      {
        id: 'examinations-schedule',
        title: 'Schedule',
        path: '/admin/examinations/schedule',
        icon: <CalendarIcon />,
      },
      {
        id: 'examinations-results',
        title: 'Results',
        path: '/admin/examinations/results',
        icon: <GradeIcon />,
      },
      {
        id: 'examinations-analysis',
        title: 'Analysis',
        path: '/admin/examinations/analysis',
        icon: <AnalyticsIcon />,
      },
    ],
  },
  {
    id: 'previous-year-papers',
    title: 'Previous Year Papers',
    icon: <BookIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
    children: [
      {
        id: 'papers-list',
        title: 'All Papers',
        path: '/admin/papers/list',
        icon: <BookIcon />,
      },
      {
        id: 'papers-upload',
        title: 'Upload Paper',
        path: '/admin/papers/upload',
        icon: <BookIcon />,
        roles: ['admin', 'institution_admin', 'teacher'],
      },
      {
        id: 'question-bank',
        title: 'Question Bank',
        path: '/admin/papers/question-bank',
        icon: <AssignmentIcon />,
      },
    ],
  },
  {
    id: 'ai-prediction',
    title: 'AI Exam Prediction',
    path: '/student/ai-prediction',
    icon: <AIIcon />,
    roles: ['student'],
    badge: 'NEW',
  },
  {
    id: 'attendance',
    title: 'Attendance',
    path: '/admin/attendance',
    icon: <CalendarIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
    children: [
      {
        id: 'attendance-mark',
        title: 'Mark Attendance',
        path: '/admin/attendance/mark',
        icon: <CheckCircleIcon />,
        roles: ['admin', 'institution_admin', 'teacher'],
      },
      {
        id: 'attendance-sheet',
        title: 'Attendance Sheet',
        path: '/admin/attendance/sheet',
        icon: <CalendarTodayIcon />,
        roles: ['admin', 'institution_admin', 'teacher'],
      },
      {
        id: 'attendance-defaulters',
        title: 'Defaulters Report',
        path: '/admin/attendance/defaulters',
        icon: <WarningIcon />,
        roles: ['admin', 'institution_admin', 'teacher'],
      },
      {
        id: 'attendance-corrections',
        title: 'Corrections',
        path: '/admin/attendance/corrections',
        icon: <EditIcon />,
        roles: ['admin', 'institution_admin', 'teacher'],
      },
    ],
  },
  {
    id: 'pomodoro',
    title: 'Pomodoro Timer',
    path: '/student/pomodoro',
    icon: <TimerIcon />,
    roles: ['student'],
    badge: 'NEW',
  },
  {
    id: 'goals',
    title: 'Goals',
    path: '/admin/goals',
    icon: <GoalIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
  },
  {
    id: 'gamification',
    title: 'Gamification',
    icon: <AchievementsIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
    children: [
      {
        id: 'gamification-achievements',
        title: 'Achievements',
        path: '/admin/gamification/achievements',
        icon: <AchievementsIcon />,
      },
      {
        id: 'gamification-leaderboard',
        title: 'Leaderboard',
        path: '/admin/gamification/leaderboard',
        icon: <AnalyticsIcon />,
      },
    ],
  },
  {
    id: 'communication',
    title: 'Communication',
    icon: <ForumIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
    children: [
      {
        id: 'communication-announcements',
        title: 'Announcements',
        path: '/admin/communication/announcements',
        icon: <NotificationsIcon />,
        badge: 3,
      },
      {
        id: 'communication-messages',
        title: 'Messages',
        path: '/admin/communication/messages',
        icon: <ForumIcon />,
      },
    ],
  },
  {
    id: 'flashcards',
    title: 'Flashcards',
    path: '/admin/flashcards',
    icon: <BookIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
  },
  {
    id: 'quizzes',
    title: 'Quizzes',
    path: '/admin/quizzes',
    icon: <AssignmentIcon />,
    roles: ['admin', 'institution_admin', 'teacher', 'student'],
  },
  {
    id: 'analytics',
    title: 'Analytics',
    path: '/admin/analytics',
    icon: <AnalyticsIcon />,
    roles: ['admin', 'institution_admin', 'teacher'],
  },
  {
    id: 'subscription',
    title: 'Subscription & Billing',
    path: '/admin/subscription',
    icon: <PaymentIcon />,
    roles: ['admin', 'institution_admin'],
  },
  {
    id: 'merchandise',
    title: 'Merchandise Store',
    path: '/admin/merchandise',
    icon: <StoreIcon />,
    roles: ['admin', 'institution_admin'],
  },
  {
    id: 'data-management',
    title: 'Data Management',
    icon: <ImportIcon />,
    roles: ['admin', 'institution_admin'],
    children: [
      {
        id: 'data-export',
        title: 'Export Data',
        path: '/admin/data/export',
        icon: <ExportIcon />,
      },
      {
        id: 'data-import',
        title: 'Import Data',
        path: '/admin/data/import',
        icon: <ImportIcon />,
      },
    ],
  },
  {
    id: 'settings',
    title: 'Settings',
    path: '/admin/settings',
    icon: <SettingsIcon />,
    roles: ['admin', 'institution_admin'],
  },
];
