#!/bin/bash

# Script to set up a separate test database for migration testing
# This creates a clean test database environment

set -e

# Load environment variables from .env file if it exists
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Default values
TEST_DATABASE_NAME="${TEST_DATABASE_NAME:-fastapi_db_migration_test}"
DATABASE_HOST="${DATABASE_HOST:-localhost}"
DATABASE_PORT="${DATABASE_PORT:-3306}"
DATABASE_USER="${DATABASE_USER:-root}"
DATABASE_PASSWORD="${DATABASE_PASSWORD:-test_password}"

echo "============================================"
echo "Migration Test Database Setup"
echo "============================================"
echo "Host: $DATABASE_HOST"
echo "Port: $DATABASE_PORT"
echo "User: $DATABASE_USER"
echo "Test Database: $TEST_DATABASE_NAME"
echo "============================================"

# Check if MySQL is accessible
echo "Checking MySQL connection..."
if ! mysql -h "$DATABASE_HOST" -P "$DATABASE_PORT" -u "$DATABASE_USER" -p"$DATABASE_PASSWORD" -e "SELECT 1" > /dev/null 2>&1; then
    echo "ERROR: Cannot connect to MySQL server"
    echo "Please ensure MySQL is running and credentials are correct"
    exit 1
fi

echo "✓ MySQL connection successful"

# Drop test database if it exists
echo "Dropping existing test database if it exists..."
mysql -h "$DATABASE_HOST" -P "$DATABASE_PORT" -u "$DATABASE_USER" -p"$DATABASE_PASSWORD" -e "DROP DATABASE IF EXISTS \`$TEST_DATABASE_NAME\`;" > /dev/null 2>&1 || true

# Create new test database
echo "Creating test database..."
mysql -h "$DATABASE_HOST" -P "$DATABASE_PORT" -u "$DATABASE_USER" -p"$DATABASE_PASSWORD" -e "CREATE DATABASE \`$TEST_DATABASE_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" > /dev/null 2>&1

echo "✓ Test database created successfully"

# Grant necessary privileges
echo "Setting up database permissions..."
mysql -h "$DATABASE_HOST" -P "$DATABASE_PORT" -u "$DATABASE_USER" -p"$DATABASE_PASSWORD" << EOF > /dev/null 2>&1
GRANT ALL PRIVILEGES ON \`$TEST_DATABASE_NAME\`.* TO '$DATABASE_USER'@'%';
FLUSH PRIVILEGES;
EOF

echo "✓ Database permissions configured"

# Set up test database configuration file
TEST_ENV_FILE=".env.test.migration"
cat > "$TEST_ENV_FILE" << EOF
# Migration Test Database Configuration
# Auto-generated by setup_test_db.sh

DATABASE_HOST=$DATABASE_HOST
DATABASE_PORT=$DATABASE_PORT
DATABASE_USER=$DATABASE_USER
DATABASE_PASSWORD=$DATABASE_PASSWORD
DATABASE_NAME=$TEST_DATABASE_NAME
EOF

echo "✓ Test environment configuration saved to $TEST_ENV_FILE"

echo ""
echo "============================================"
echo "Test database setup completed successfully!"
echo "============================================"
echo ""
echo "Next steps:"
echo "1. Run schema backup: ./scripts/migration_test/backup_production_schema.sh"
echo "2. Run migration validation: python scripts/migration_test/validate_migrations.py"
echo ""
