#!/bin/bash

# Script to set up a separate test database for migration testing
# This creates a clean test database environment

set -e

# Load environment variables from .env file if it exists
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Default values
TEST_DATABASE_NAME="${TEST_DATABASE_NAME:-fastapi_db_migration_test}"
DATABASE_HOST="${DATABASE_HOST:-localhost}"
DATABASE_PORT="${DATABASE_PORT:-5432}"
DATABASE_USER="${DATABASE_USER:-postgres}"
PGPASSWORD="${DATABASE_PASSWORD:-postgres}"

export PGPASSWORD

echo "============================================"
echo "Migration Test Database Setup"
echo "============================================"
echo "Host: $DATABASE_HOST"
echo "Port: $DATABASE_PORT"
echo "User: $DATABASE_USER"
echo "Test Database: $TEST_DATABASE_NAME"
echo "============================================"

# Check if PostgreSQL is accessible
echo "Checking PostgreSQL connection..."
if ! psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -d postgres -c "SELECT 1" > /dev/null 2>&1; then
    echo "ERROR: Cannot connect to PostgreSQL server"
    echo "Please ensure PostgreSQL is running and credentials are correct"
    exit 1
fi

echo "✓ PostgreSQL connection successful"

# Drop test database if it exists
echo "Dropping existing test database if it exists..."
psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -d postgres -c "DROP DATABASE IF EXISTS $TEST_DATABASE_NAME;" > /dev/null 2>&1 || true

# Create new test database
echo "Creating test database..."
psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -d postgres -c "CREATE DATABASE $TEST_DATABASE_NAME;" > /dev/null 2>&1

echo "✓ Test database created successfully"

# Grant necessary privileges
echo "Setting up database permissions..."
psql -h "$DATABASE_HOST" -p "$DATABASE_PORT" -U "$DATABASE_USER" -d postgres << EOF > /dev/null 2>&1
GRANT ALL PRIVILEGES ON DATABASE $TEST_DATABASE_NAME TO $DATABASE_USER;
EOF

echo "✓ Database permissions configured"

# Set up test database configuration file
TEST_ENV_FILE=".env.test.migration"
cat > "$TEST_ENV_FILE" << EOF
# Migration Test Database Configuration
# Auto-generated by setup_test_db.sh

DATABASE_HOST=$DATABASE_HOST
DATABASE_PORT=$DATABASE_PORT
DATABASE_USER=$DATABASE_USER
DATABASE_PASSWORD=$DATABASE_PASSWORD
DATABASE_NAME=$TEST_DATABASE_NAME
EOF

echo "✓ Test environment configuration saved to $TEST_ENV_FILE"

echo ""
echo "============================================"
echo "Test database setup completed successfully!"
echo "============================================"
echo ""
echo "Next steps:"
echo "1. Run schema backup: ./scripts/migration_test/backup_production_schema.sh"
echo "2. Run migration validation: python scripts/migration_test/validate_migrations.py"
echo ""
