# PowerShell script to set up a separate test database for migration testing
# This creates a clean test database environment

param(
    [string]$TestDatabaseName = "fastapi_db_migration_test",
    [string]$DatabaseHost = "localhost",
    [int]$DatabasePort = 3306,
    [string]$DatabaseUser = "root",
    [string]$DatabasePassword = "test_password"
)

# Load environment variables from .env file if it exists
if (Test-Path .env) {
    Get-Content .env | ForEach-Object {
        if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
            $name = $matches[1].Trim()
            $value = $matches[2].Trim()
            Set-Item -Path "env:$name" -Value $value
        }
    }
}

# Override with environment variables if set
if ($env:TEST_DATABASE_NAME) { $TestDatabaseName = $env:TEST_DATABASE_NAME }
if ($env:DATABASE_HOST) { $DatabaseHost = $env:DATABASE_HOST }
if ($env:DATABASE_PORT) { $DatabasePort = $env:DATABASE_PORT }
if ($env:DATABASE_USER) { $DatabaseUser = $env:DATABASE_USER }
if ($env:DATABASE_PASSWORD) { $DatabasePassword = $env:DATABASE_PASSWORD }

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Migration Test Database Setup" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Host: $DatabaseHost"
Write-Host "Port: $DatabasePort"
Write-Host "User: $DatabaseUser"
Write-Host "Test Database: $TestDatabaseName"
Write-Host "============================================" -ForegroundColor Cyan

# Check if MySQL is accessible
Write-Host "Checking MySQL connection..."
try {
    $null = & mysql -h $DatabaseHost -P $DatabasePort -u $DatabaseUser -p"$DatabasePassword" -e "SELECT 1" 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Connection failed"
    }
    Write-Host "✓ MySQL connection successful" -ForegroundColor Green
} catch {
    Write-Host "ERROR: Cannot connect to MySQL server" -ForegroundColor Red
    Write-Host "Please ensure MySQL is running and credentials are correct" -ForegroundColor Red
    exit 1
}

# Drop test database if it exists
Write-Host "Dropping existing test database if it exists..."
$null = & mysql -h $DatabaseHost -P $DatabasePort -u $DatabaseUser -p"$DatabasePassword" -e "DROP DATABASE IF EXISTS ``$TestDatabaseName``;" 2>&1

# Create new test database
Write-Host "Creating test database..."
$null = & mysql -h $DatabaseHost -P $DatabasePort -u $DatabaseUser -p"$DatabasePassword" -e "CREATE DATABASE ``$TestDatabaseName`` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Failed to create test database" -ForegroundColor Red
    exit 1
}
Write-Host "✓ Test database created successfully" -ForegroundColor Green

# Grant necessary privileges
Write-Host "Setting up database permissions..."
$grantSQL = @"
GRANT ALL PRIVILEGES ON ``$TestDatabaseName``.* TO '$DatabaseUser'@'%';
FLUSH PRIVILEGES;
"@
$null = & mysql -h $DatabaseHost -P $DatabasePort -u $DatabaseUser -p"$DatabasePassword" -e $grantSQL 2>&1
Write-Host "✓ Database permissions configured" -ForegroundColor Green

# Set up test database configuration file
$TestEnvFile = ".env.test.migration"
@"
# Migration Test Database Configuration
# Auto-generated by setup_test_db.ps1

DATABASE_HOST=$DatabaseHost
DATABASE_PORT=$DatabasePort
DATABASE_USER=$DatabaseUser
DATABASE_PASSWORD=$DatabasePassword
DATABASE_NAME=$TestDatabaseName
"@ | Out-File -FilePath $TestEnvFile -Encoding utf8

Write-Host "✓ Test environment configuration saved to $TestEnvFile" -ForegroundColor Green

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Test database setup completed successfully!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Run schema backup: .\scripts\migration_test\backup_production_schema.ps1"
Write-Host "2. Run migration validation: python scripts\migration_test\validate_migrations.py"
Write-Host ""
