"""
Clean and Sanitize Autogenerated Migration

This script helps review and clean autogenerated migrations by:
1. Analyzing the migration file for common issues
2. Detecting false positives
3. Adding safety checks
4. Making operations idempotent

Usage:
    python scripts/clean_autogenerated_migration.py <migration_file>
    python scripts/clean_autogenerated_migration.py alembic/versions/041_sync_database_with_models.py
"""

import argparse
import re
import sys
from pathlib import Path
from typing import List, Dict, Set, Tuple


class MigrationCleaner:
    def __init__(self, migration_file: Path):
        self.migration_file = migration_file
        self.content = migration_file.read_text()
        self.issues = []
        self.suggestions = []
        
    def analyze(self):
        """Analyze the migration for common issues"""
        print(f"\n{'='*80}")
        print(f"Analyzing: {self.migration_file.name}")
        print(f"{'='*80}\n")
        
        self.check_drop_operations()
        self.check_enum_operations()
        self.check_table_operations()
        self.check_foreign_key_operations()
        self.check_index_operations()
        self.check_alter_column_operations()
        self.check_data_migration_needs()
        
        self.print_report()
        
    def check_drop_operations(self):
        """Check for potentially dangerous drop operations"""
        drop_patterns = [
            (r'op\.drop_table\(["\'](\w+)["\']\)', 'drop_table'),
            (r'op\.drop_column\(["\'](\w+)["\']\s*,\s*["\'](\w+)["\']\)', 'drop_column'),
            (r'op\.drop_constraint\(["\'](\w+)["\']', 'drop_constraint'),
            (r'op\.drop_index\(["\'](\w+)["\']', 'drop_index'),
        ]
        
        for pattern, op_type in drop_patterns:
            matches = re.finditer(pattern, self.content)
            for match in matches:
                self.issues.append({
                    'severity': 'HIGH',
                    'type': 'DROP_OPERATION',
                    'operation': op_type,
                    'target': match.group(1) if op_type == 'drop_table' else match.group(0),
                    'message': f'Found {op_type} operation - verify this is intentional',
                    'suggestion': f'Consider if this drop is a false positive. If so, comment it out.'
                })
    
    def check_enum_operations(self):
        """Check for enum type operations that might fail"""
        # Check for CREATE TYPE without existence check
        create_enum_pattern = r'op\.execute\(["\']CREATE TYPE (\w+)'
        matches = re.finditer(create_enum_pattern, self.content)
        
        for match in matches:
            enum_name = match.group(1)
            # Check if there's already an existence check nearby
            context = self.content[max(0, match.start()-500):match.end()+100]
            if 'pg_type' not in context and 'EXISTS' not in context.upper():
                self.issues.append({
                    'severity': 'MEDIUM',
                    'type': 'ENUM_WITHOUT_CHECK',
                    'target': enum_name,
                    'message': f'Creating enum type "{enum_name}" without existence check',
                    'suggestion': 'Add existence check before creating enum type'
                })
                
                self.suggestions.append({
                    'type': 'enum_check',
                    'enum_name': enum_name,
                    'code': self.generate_enum_check_code(enum_name)
                })
    
    def check_table_operations(self):
        """Check for table creation operations"""
        create_table_pattern = r'op\.create_table\(["\'](\w+)["\']'
        matches = re.finditer(create_table_pattern, self.content)
        
        for match in matches:
            table_name = match.group(1)
            # Check if there's an existence check
            context = self.content[max(0, match.start()-500):match.end()+100]
            if 'information_schema.tables' not in context and 'EXISTS' not in context.upper():
                self.issues.append({
                    'severity': 'MEDIUM',
                    'type': 'TABLE_WITHOUT_CHECK',
                    'target': table_name,
                    'message': f'Creating table "{table_name}" without existence check',
                    'suggestion': 'Add existence check before creating table for idempotency'
                })
                
                self.suggestions.append({
                    'type': 'table_check',
                    'table_name': table_name,
                    'code': self.generate_table_check_code(table_name)
                })
    
    def check_foreign_key_operations(self):
        """Check for foreign key operations"""
        fk_pattern = r'op\.create_foreign_key\(["\'](\w+)["\']'
        matches = re.finditer(fk_pattern, self.content)
        
        for match in matches:
            fk_name = match.group(1)
            self.issues.append({
                'severity': 'LOW',
                'type': 'FOREIGN_KEY',
                'target': fk_name,
                'message': f'Creating foreign key "{fk_name}"',
                'suggestion': 'Verify foreign key constraint doesn\'t already exist'
            })
    
    def check_index_operations(self):
        """Check for index operations"""
        index_pattern = r'op\.create_index\(["\'](\w+)["\']'
        matches = re.finditer(index_pattern, self.content)
        
        for match in matches:
            index_name = match.group(1)
            # Check if there's an existence check
            context = self.content[max(0, match.start()-500):match.end()+100]
            if 'pg_indexes' not in context and 'EXISTS' not in context.upper():
                self.issues.append({
                    'severity': 'LOW',
                    'type': 'INDEX_WITHOUT_CHECK',
                    'target': index_name,
                    'message': f'Creating index "{index_name}" without existence check',
                    'suggestion': 'Add existence check to prevent duplicate index errors'
                })
    
    def check_alter_column_operations(self):
        """Check for column alteration operations"""
        alter_patterns = [
            (r'op\.alter_column\(["\'](\w+)["\']', 'alter_column'),
            (r'alter_column.*nullable=False', 'set_not_null'),
            (r'alter_column.*type_=', 'change_type'),
        ]
        
        for pattern, op_type in alter_patterns:
            matches = re.finditer(pattern, self.content, re.IGNORECASE)
            for match in matches:
                self.issues.append({
                    'severity': 'HIGH',
                    'type': 'ALTER_COLUMN',
                    'operation': op_type,
                    'target': match.group(0)[:100],
                    'message': f'Altering column - may impact existing data',
                    'suggestion': 'Verify this change is safe and won\'t lose data'
                })
    
    def check_data_migration_needs(self):
        """Check if data migration might be needed"""
        data_migration_indicators = [
            (r'nullable=False', 'Setting NOT NULL'),
            (r'unique=True', 'Adding UNIQUE constraint'),
            (r'\.Enum\(', 'Using enum type'),
        ]
        
        for pattern, description in data_migration_indicators:
            if re.search(pattern, self.content):
                self.issues.append({
                    'severity': 'MEDIUM',
                    'type': 'DATA_MIGRATION',
                    'operation': description,
                    'message': f'{description} - may require data migration',
                    'suggestion': 'Ensure existing data complies with new constraints'
                })
    
    def generate_enum_check_code(self, enum_name: str) -> str:
        """Generate code for safe enum creation"""
        return f"""
    # Check if enum type exists before creating
    conn = op.get_bind()
    result = conn.execute(
        "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{enum_name}')"
    ).scalar()
    
    if not result:
        # Create enum type
        op.execute("CREATE TYPE {enum_name} AS ENUM (...)")
"""
    
    def generate_table_check_code(self, table_name: str) -> str:
        """Generate code for safe table creation"""
        return f"""
    # Check if table exists before creating
    conn = op.get_bind()
    result = conn.execute(
        \"\"\"
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables 
            WHERE table_name = '{table_name}'
        )
        \"\"\"
    ).scalar()
    
    if not result:
        # Create table
        op.create_table('{table_name}', ...)
"""
    
    def print_report(self):
        """Print analysis report"""
        # Group issues by severity
        high_issues = [i for i in self.issues if i['severity'] == 'HIGH']
        medium_issues = [i for i in self.issues if i['severity'] == 'MEDIUM']
        low_issues = [i for i in self.issues if i['severity'] == 'LOW']
        
        print(f"Analysis Results:")
        print(f"  Total Issues: {len(self.issues)}")
        print(f"  High Priority: {len(high_issues)}")
        print(f"  Medium Priority: {len(medium_issues)}")
        print(f"  Low Priority: {len(low_issues)}")
        print()
        
        if high_issues:
            print(f"{'='*80}")
            print("HIGH PRIORITY ISSUES (Must Review)")
            print(f"{'='*80}\n")
            for issue in high_issues:
                print(f"⚠️  {issue['type']}: {issue['message']}")
                print(f"   Target: {issue['target']}")
                print(f"   Suggestion: {issue['suggestion']}")
                print()
        
        if medium_issues:
            print(f"{'='*80}")
            print("MEDIUM PRIORITY ISSUES (Should Review)")
            print(f"{'='*80}\n")
            for issue in medium_issues:
                print(f"⚡ {issue['type']}: {issue['message']}")
                if 'target' in issue:
                    print(f"   Target: {issue['target']}")
                print(f"   Suggestion: {issue['suggestion']}")
                print()
        
        if low_issues:
            print(f"{'='*80}")
            print("LOW PRIORITY ISSUES (Review if Time Permits)")
            print(f"{'='*80}\n")
            for issue in low_issues[:5]:  # Show first 5
                print(f"ℹ️  {issue['type']}: {issue['message']}")
                print(f"   Target: {issue['target']}")
                print()
            
            if len(low_issues) > 5:
                print(f"   ... and {len(low_issues) - 5} more low priority issues")
                print()
        
        if self.suggestions:
            print(f"{'='*80}")
            print("CODE SUGGESTIONS")
            print(f"{'='*80}\n")
            
            print("Add these safety checks to your migration:\n")
            
            for suggestion in self.suggestions[:3]:  # Show first 3
                print(f"For {suggestion['type']} - {suggestion.get('enum_name') or suggestion.get('table_name')}:")
                print(suggestion['code'])
                print()
        
        # Final recommendations
        print(f"{'='*80}")
        print("RECOMMENDATIONS")
        print(f"{'='*80}\n")
        
        recommendations = [
            "1. Review all DROP operations - ensure they are intentional",
            "2. Add existence checks for enum types and tables",
            "3. Test on a clean database first",
            "4. Test on a copy of production database",
            "5. Verify data integrity after migration",
            "6. Test the downgrade() function",
            "7. Document any manual steps required",
        ]
        
        for rec in recommendations:
            print(f"  {rec}")
        
        print()
        
    def generate_cleaned_version(self, output_file: Path = None):
        """Generate a cleaned version with safety checks added"""
        if output_file is None:
            output_file = self.migration_file.parent / f"{self.migration_file.stem}_cleaned.py"
        
        # This would require more sophisticated code manipulation
        # For now, just provide guidance
        print(f"\n{'='*80}")
        print("To create a cleaned version:")
        print(f"{'='*80}\n")
        print(f"1. Copy {self.migration_file.name} to {output_file.name}")
        print(f"2. Apply the suggestions above")
        print(f"3. Test thoroughly")
        print(f"4. Replace the original if tests pass")
        print()


def main():
    parser = argparse.ArgumentParser(
        description="Analyze and clean autogenerated Alembic migrations"
    )
    
    parser.add_argument(
        "migration_file",
        type=Path,
        help="Path to the migration file to analyze"
    )
    
    parser.add_argument(
        "--output",
        type=Path,
        help="Output file for cleaned version (optional)"
    )
    
    args = parser.parse_args()
    
    if not args.migration_file.exists():
        print(f"Error: File not found: {args.migration_file}")
        sys.exit(1)
    
    cleaner = MigrationCleaner(args.migration_file)
    cleaner.analyze()
    
    if args.output:
        cleaner.generate_cleaned_version(args.output)


if __name__ == "__main__":
    main()
