"""
Generate Clean Autogenerated Migration Script

This script implements the workflow for generating a clean autogenerated migration
when the migration chain is too broken to repair incrementally:

1. Stamp database with current migration head using `alembic stamp head`
2. Create new autogenerated migration with `alembic revision --autogenerate -m "sync_database_with_models"`
3. Review autogenerated migration for correctness (may include false positives)
4. Edit migration to remove unwanted changes
5. Test on clean database
6. Apply to fix schema drift

Usage:
    python scripts/generate_clean_migration.py [--stamp-only] [--generate-only] [--review]

Options:
    --stamp-only      Only stamp the database to current head
    --generate-only   Only generate the migration file (don't stamp first)
    --review         Review the generated migration and prompt for edits
    --help           Show this help message
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from datetime import datetime


class MigrationGenerator:
    def __init__(self, project_root=None):
        self.project_root = Path(project_root or os.getcwd())
        self.alembic_dir = self.project_root / "alembic"
        self.versions_dir = self.alembic_dir / "versions"
        
    def run_command(self, cmd, description=None):
        """Run a shell command and capture output"""
        if description:
            print(f"\n{'='*80}")
            print(f"{description}")
            print(f"{'='*80}")
        
        print(f"Running: {' '.join(cmd)}")
        
        try:
            result = subprocess.run(
                cmd,
                cwd=str(self.project_root),
                capture_output=True,
                text=True,
                check=True
            )
            
            if result.stdout:
                print(result.stdout)
            
            return True, result.stdout
            
        except subprocess.CalledProcessError as e:
            print(f"Error: {e}")
            if e.stdout:
                print(f"STDOUT: {e.stdout}")
            if e.stderr:
                print(f"STDERR: {e.stderr}")
            return False, None
    
    def check_alembic_installed(self):
        """Verify alembic is installed and accessible"""
        success, _ = self.run_command(
            ["alembic", "--version"],
            "Checking Alembic installation"
        )
        return success
    
    def get_current_revision(self):
        """Get the current database revision"""
        print("\n" + "="*80)
        print("Checking current database revision")
        print("="*80)
        
        success, output = self.run_command(
            ["alembic", "current"],
            None
        )
        
        if success:
            print(f"Current revision info:\n{output}")
            return True, output
        else:
            print("Warning: Could not determine current revision")
            return False, None
    
    def stamp_head(self):
        """Stamp the database with the current head revision"""
        success, _ = self.run_command(
            ["alembic", "stamp", "head"],
            "Stamping database to HEAD"
        )
        
        if success:
            print("\n✓ Database successfully stamped to HEAD")
            print("  This marks the database as being at the latest migration")
            print("  without actually running any migrations.")
        else:
            print("\n✗ Failed to stamp database")
            print("  Check that the database is accessible and alembic.ini is configured correctly")
        
        return success
    
    def generate_autogenerated_migration(self, message="sync_database_with_models"):
        """Generate an autogenerated migration"""
        success, output = self.run_command(
            ["alembic", "revision", "--autogenerate", "-m", message],
            "Generating autogenerated migration"
        )
        
        if success:
            print("\n✓ Migration file generated successfully")
            
            # Try to find the newly created migration file
            migration_file = self.find_latest_migration()
            if migration_file:
                print(f"\nGenerated migration: {migration_file}")
                return True, migration_file
        else:
            print("\n✗ Failed to generate migration")
            print("  Check that:")
            print("  - Database connection is working")
            print("  - All model files are importable")
            print("  - alembic/env.py is configured correctly")
        
        return success, None
    
    def find_latest_migration(self):
        """Find the most recently created migration file"""
        if not self.versions_dir.exists():
            return None
        
        migration_files = list(self.versions_dir.glob("*.py"))
        if not migration_files:
            return None
        
        # Sort by modification time, most recent first
        latest = max(migration_files, key=lambda p: p.stat().st_mtime)
        return latest
    
    def review_migration(self, migration_file):
        """Display migration file content for review"""
        print("\n" + "="*80)
        print(f"Migration File: {migration_file.name}")
        print("="*80)
        
        try:
            content = migration_file.read_text()
            print(content)
            
            print("\n" + "="*80)
            print("Review Checklist:")
            print("="*80)
            print("""
1. Check for false positives:
   - Tables/columns that shouldn't be created/dropped
   - Indexes that already exist
   - Foreign keys that are already in place
   - Enum types that already exist
   
2. Verify actual schema drift:
   - Missing tables from new models
   - Missing columns from model updates
   - Missing indexes on foreign keys
   - Missing constraints
   
3. Look for common issues:
   - Dropping tables that shouldn't be dropped
   - Altering columns that don't need changes
   - Recreating existing enums
   - Duplicate foreign key constraints
   
4. Data safety:
   - Are there any DROP operations?
   - Are there ALTER COLUMN operations that could lose data?
   - Are there any operations that require data migration first?
   
5. Performance impact:
   - Large table alterations that might lock tables
   - Index creation on large tables (consider CONCURRENTLY)
   - Enum additions that might require table rewrites
            """)
            
            return True
            
        except Exception as e:
            print(f"Error reading migration file: {e}")
            return False
    
    def get_migration_edit_guidance(self):
        """Provide guidance on editing the migration"""
        print("\n" + "="*80)
        print("Editing the Migration")
        print("="*80)
        print("""
Common edits to make:

1. Remove false positive drops:
   If the migration wants to drop existing tables/columns, comment them out:
   
   # op.drop_table('existing_table')  # False positive - table should stay
   
2. Add existence checks for enums:
   
   # Before:
   op.execute("CREATE TYPE myenum AS ENUM ('value1', 'value2')")
   
   # After:
   conn = op.get_bind()
   result = conn.execute(
       "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'myenum')"
   ).scalar()
   if not result:
       op.execute("CREATE TYPE myenum AS ENUM ('value1', 'value2')")
   
3. Add existence checks for tables:
   
   result = conn.execute(
       "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'mytable')"
   ).scalar()
   if not result:
       op.create_table(...)
   
4. Make operations idempotent:
   - Check before creating indexes
   - Check before adding constraints
   - Check before creating foreign keys
   
5. Add safety comments:
   Document why operations are included or excluded

6. Test data impact:
   For any ALTER operations, verify they won't lose data
        """)
    
    def suggest_testing_steps(self, migration_file):
        """Suggest steps for testing the migration"""
        print("\n" + "="*80)
        print("Testing the Migration")
        print("="*80)
        
        revision_id = migration_file.stem.split('_')[0] if migration_file else "new_revision"
        
        print(f"""
Recommended testing workflow:

1. Test on a clean database:
   
   # Create a fresh test database
   createdb test_migration_db
   
   # Run all migrations from scratch
   alembic upgrade head
   
   # Verify everything works
   python scripts/diagnose_migrations.py

2. Test on a database copy:
   
   # Create a copy of production/staging DB
   pg_dump production_db > backup.sql
   createdb test_existing_db
   psql test_existing_db < backup.sql
   
   # Run the new migration
   alembic upgrade {revision_id}
   
   # Verify the changes
   psql test_existing_db -c "\\dt"  # List tables
   psql test_existing_db -c "\\d+ tablename"  # Describe specific tables

3. Run downgrade test:
   
   # Test rollback
   alembic downgrade -1
   
   # Verify database is intact
   # Test upgrade again
   alembic upgrade head

4. Check for data integrity:
   
   # Run integrity checks
   python scripts/check_database_integrity.py
   
   # Check for orphaned records
   # Verify foreign key constraints
   # Test application functionality

5. Performance testing:
   
   # Time the migration
   time alembic upgrade {revision_id}
   
   # Check for table locks
   # Verify index creation didn't timeout
   # Test query performance on affected tables

6. Production preparation:
   
   # Create backup plan
   pg_dump production_db > pre_migration_backup.sql
   
   # Schedule maintenance window if needed
   # Prepare rollback script
   # Document expected downtime
        """)
    
    def run_full_workflow(self, args):
        """Run the complete migration generation workflow"""
        print("\n" + "="*80)
        print("Clean Autogenerated Migration Workflow")
        print("="*80)
        print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        # Check prerequisites
        if not self.check_alembic_installed():
            print("\n✗ Alembic is not installed or not in PATH")
            print("  Install with: pip install alembic")
            return False
        
        # Step 0: Show current state
        self.get_current_revision()
        
        # Step 1: Stamp database (unless --generate-only)
        if not args.generate_only:
            print("\n" + "="*80)
            print("Step 1: Stamp Database to HEAD")
            print("="*80)
            print("This marks the database as being at the latest migration")
            print("without running any actual migrations.")
            print()
            
            if not self.stamp_head():
                print("\n✗ Workflow aborted: Could not stamp database")
                return False
        
        if args.stamp_only:
            print("\n✓ Database stamped successfully (stamp-only mode)")
            return True
        
        # Step 2: Generate autogenerated migration
        print("\n" + "="*80)
        print("Step 2: Generate Autogenerated Migration")
        print("="*80)
        print("This will compare the current database schema with SQLAlchemy models")
        print("and generate a migration to sync them.")
        print()
        
        success, migration_file = self.generate_autogenerated_migration()
        if not success or not migration_file:
            print("\n✗ Workflow aborted: Could not generate migration")
            return False
        
        # Step 3: Review the migration
        if args.review or True:  # Always review by default
            print("\n" + "="*80)
            print("Step 3: Review Generated Migration")
            print("="*80)
            
            self.review_migration(migration_file)
            
            # Step 4: Provide editing guidance
            self.get_migration_edit_guidance()
            
            # Step 5: Provide testing guidance
            self.suggest_testing_steps(migration_file)
        
        print("\n" + "="*80)
        print("Workflow Complete")
        print("="*80)
        print(f"""
✓ Migration generated: {migration_file.name}

Next steps:

1. Review the migration file carefully
2. Edit to remove false positives and add safety checks
3. Test on a clean database
4. Test on a copy of existing database
5. Test downgrade/upgrade cycle
6. Apply to production after testing

To apply the migration:
    alembic upgrade head

To rollback:
    alembic downgrade -1
        """)
        
        return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate clean autogenerated migration for schema sync",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        "--stamp-only",
        action="store_true",
        help="Only stamp the database to current head"
    )
    
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="Only generate the migration file (don't stamp first)"
    )
    
    parser.add_argument(
        "--review",
        action="store_true",
        help="Review the generated migration and show editing guidance"
    )
    
    args = parser.parse_args()
    
    # Validate argument combinations
    if args.stamp_only and args.generate_only:
        print("Error: Cannot use both --stamp-only and --generate-only")
        sys.exit(1)
    
    # Run the workflow
    generator = MigrationGenerator()
    success = generator.run_full_workflow(args)
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
