#!/bin/bash

# Schema Sync Workflow Script
# This script automates the complete workflow for syncing database schema with models
# when schema drift is detected or migration chain needs repair.

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "${BLUE}================================================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================================================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "$1"
}

confirm() {
    read -p "$(echo -e ${YELLOW}$1${NC}) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        return 1
    fi
    return 0
}

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"
    
    # Check if virtual environment is activated
    if [[ -z "$VIRTUAL_ENV" ]]; then
        print_error "Virtual environment not activated"
        print_info "Please activate your virtual environment first:"
        print_info "  source .venv/bin/activate  # Linux/Mac"
        print_info "  .venv\\Scripts\\activate    # Windows"
        exit 1
    fi
    print_success "Virtual environment activated: $VIRTUAL_ENV"
    
    # Check if alembic is installed
    if ! python -c "import alembic" 2>/dev/null; then
        print_error "Alembic not installed"
        print_info "Install with: pip install alembic"
        exit 1
    fi
    print_success "Alembic installed"
    
    # Check if database connection works
    if ! alembic current >/dev/null 2>&1; then
        print_error "Cannot connect to database"
        print_info "Check your database connection settings in .env"
        exit 1
    fi
    print_success "Database connection OK"
    
    echo
}

# Show current state
show_current_state() {
    print_header "Current Database State"
    
    echo "Current revision:"
    alembic current || true
    
    echo
    echo "Recent migration history (last 5):"
    alembic history --verbose | head -20 || true
    
    echo
}

# Backup database
backup_database() {
    print_header "Database Backup"
    
    if confirm "Create database backup before proceeding? (recommended) [y/n]: "; then
        local backup_file="backup_$(date +%Y%m%d_%H%M%S).sql"
        
        # Extract database info from DATABASE_URL or ask user
        if [[ -n "$DATABASE_URL" ]]; then
            print_info "Creating backup..."
            # This is a simplified version - adapt based on your database type
            pg_dump $DATABASE_URL > "$backup_file" 2>/dev/null || {
                print_warning "Automatic backup failed. Please create backup manually."
                if ! confirm "Continue without automatic backup? [y/n]: "; then
                    exit 1
                fi
            }
            print_success "Backup created: $backup_file"
        else
            print_warning "DATABASE_URL not set. Please create backup manually."
            if ! confirm "Have you created a backup? [y/n]: "; then
                exit 1
            fi
        fi
    else
        print_warning "Proceeding without backup (not recommended)"
        if ! confirm "Are you sure? [y/n]: "; then
            exit 1
        fi
    fi
    
    echo
}

# Step 1: Stamp database
stamp_database() {
    print_header "Step 1: Stamp Database to HEAD"
    
    print_info "This will mark the database as being at the latest migration"
    print_info "without actually running any migrations."
    echo
    
    if confirm "Proceed with stamping? [y/n]: "; then
        if alembic stamp head; then
            print_success "Database stamped to HEAD"
            
            echo
            echo "Current revision after stamping:"
            alembic current
        else
            print_error "Failed to stamp database"
            exit 1
        fi
    else
        print_info "Skipping stamp step"
    fi
    
    echo
}

# Step 2: Generate migration
generate_migration() {
    print_header "Step 2: Generate Autogenerated Migration"
    
    print_info "This will compare the database schema with SQLAlchemy models"
    print_info "and generate a migration to sync them."
    echo
    
    local migration_message="${1:-sync_database_with_models}"
    
    if confirm "Proceed with migration generation? [y/n]: "; then
        if alembic revision --autogenerate -m "$migration_message"; then
            print_success "Migration generated successfully"
            
            # Find the latest migration file
            local latest_migration=$(ls -t alembic/versions/*.py | head -1)
            print_info "Generated: $latest_migration"
            
            echo
            echo "IMPORTANT: Review the generated migration before applying!"
            echo
            
            return 0
        else
            print_error "Failed to generate migration"
            exit 1
        fi
    else
        print_info "Migration generation cancelled"
        exit 0
    fi
}

# Step 3: Analyze migration
analyze_migration() {
    print_header "Step 3: Analyze Generated Migration"
    
    local latest_migration=$(ls -t alembic/versions/*.py | head -1)
    
    print_info "Running analysis on: $(basename $latest_migration)"
    echo
    
    if [[ -f "scripts/clean_autogenerated_migration.py" ]]; then
        python scripts/clean_autogenerated_migration.py "$latest_migration" || true
    else
        print_warning "Analysis script not found: scripts/clean_autogenerated_migration.py"
        print_info "Please review the migration manually"
    fi
    
    echo
}

# Step 4: Review and edit
review_migration() {
    print_header "Step 4: Review and Edit Migration"
    
    local latest_migration=$(ls -t alembic/versions/*.py | head -1)
    
    print_info "Migration file: $latest_migration"
    echo
    print_info "Review checklist:"
    print_info "  1. Check for false positive DROP operations"
    print_info "  2. Add existence checks for enums and tables"
    print_info "  3. Verify data safety for ALTER operations"
    print_info "  4. Add data migrations if needed"
    print_info "  5. Test downgrade() function"
    echo
    
    if confirm "Open migration file for editing? [y/n]: "; then
        ${EDITOR:-nano} "$latest_migration"
    fi
    
    echo
    
    if ! confirm "Have you reviewed and edited the migration? [y/n]: "; then
        print_warning "Please review the migration before proceeding"
        print_info "Migration file: $latest_migration"
        exit 0
    fi
    
    echo
}

# Step 5: Test on clean database
test_clean_database() {
    print_header "Step 5: Test on Clean Database"
    
    print_info "Testing migration on a clean database ensures all migrations"
    print_info "work correctly from scratch."
    echo
    
    print_warning "This requires a separate test database."
    print_info "You can:"
    print_info "  1. Create a test database: createdb test_migration_clean"
    print_info "  2. Set DATABASE_URL to test database"
    print_info "  3. Run: alembic upgrade head"
    print_info "  4. Verify: alembic current"
    echo
    
    if confirm "Have you tested on a clean database? [y/n]: "; then
        print_success "Clean database test completed"
    else
        print_warning "Clean database test skipped"
        print_info "It's highly recommended to test before applying to production"
    fi
    
    echo
}

# Step 6: Test on database copy
test_database_copy() {
    print_header "Step 6: Test on Database Copy"
    
    print_info "Testing on a copy of the actual database ensures the migration"
    print_info "works with real data and existing schema."
    echo
    
    print_warning "This requires a copy of your database."
    print_info "You can:"
    print_info "  1. Dump current database: pg_dump dbname > dump.sql"
    print_info "  2. Create test database: createdb test_migration_copy"
    print_info "  3. Restore dump: psql test_migration_copy < dump.sql"
    print_info "  4. Set DATABASE_URL to test database"
    print_info "  5. Run: alembic upgrade head"
    print_info "  6. Verify: alembic current"
    print_info "  7. Test rollback: alembic downgrade -1"
    echo
    
    if confirm "Have you tested on a database copy? [y/n]: "; then
        print_success "Database copy test completed"
    else
        print_warning "Database copy test skipped"
        print_info "It's highly recommended to test before applying to production"
    fi
    
    echo
}

# Step 7: Apply to production
apply_to_production() {
    print_header "Step 7: Apply to Production"
    
    print_warning "You are about to apply the migration to the production database!"
    echo
    print_info "Make sure you have:"
    print_info "  ✓ Created a backup"
    print_info "  ✓ Tested on clean database"
    print_info "  ✓ Tested on database copy"
    print_info "  ✓ Reviewed the migration code"
    print_info "  ✓ Verified rollback works"
    echo
    
    if ! confirm "Apply migration to production? [y/n]: "; then
        print_info "Migration not applied"
        exit 0
    fi
    
    print_info "Applying migration..."
    if alembic upgrade head; then
        print_success "Migration applied successfully"
        
        echo
        echo "Current revision:"
        alembic current
        
        echo
        print_success "Schema sync complete!"
    else
        print_error "Migration failed!"
        print_info "Check the error message above"
        print_info "You may need to rollback: alembic downgrade -1"
        exit 1
    fi
    
    echo
}

# Main workflow
main() {
    print_header "Schema Sync Workflow"
    print_info "This script will guide you through syncing database schema with models"
    echo
    
    # Check prerequisites
    check_prerequisites
    
    # Show current state
    show_current_state
    
    # Create backup
    backup_database
    
    # Ask which steps to perform
    print_info "Select workflow:"
    print_info "  1. Full workflow (stamp + generate + analyze)"
    print_info "  2. Stamp only"
    print_info "  3. Generate only"
    print_info "  4. Analyze existing migration"
    print_info "  5. Apply to production"
    echo
    
    read -p "Enter choice [1-5]: " choice
    echo
    
    case $choice in
        1)
            stamp_database
            generate_migration
            analyze_migration
            review_migration
            test_clean_database
            test_database_copy
            apply_to_production
            ;;
        2)
            stamp_database
            print_success "Stamp complete. You can now generate a migration."
            ;;
        3)
            generate_migration
            analyze_migration
            review_migration
            ;;
        4)
            analyze_migration
            review_migration
            ;;
        5)
            apply_to_production
            ;;
        *)
            print_error "Invalid choice"
            exit 1
            ;;
    esac
    
    print_header "Workflow Complete"
    print_success "All steps completed successfully!"
}

# Run main workflow
main "$@"
