# from src.models.institution import Institution
# from src.models.user import User
# from src.models.user_settings import UserSettings, UserDevice, AccountDeletionRequest
# from src.models.role import Role
# from src.models.permission import Permission
# from src.models.subscription import Subscription
# from src.models.audit_log import AuditLog
# from src.models.password_reset_token import PasswordResetToken
# from src.models.academic import AcademicYear, Grade, Section, Subject, GradeSubject, Chapter, Topic, DayOfWeek
# from src.models.teacher import Teacher, TeacherSubject
# from src.models.student import Student, Parent, StudentParent
# from src.models.attendance import Attendance, AttendanceCorrection, AttendanceSummary, AttendanceStatus, CorrectionStatus
# from src.models.assignment import Assignment, AssignmentFile, Submission, SubmissionFile, AssignmentStatus, SubmissionStatus
# from src.models.examination import Exam, ExamSubject, ExamSchedule, ExamMarks, ExamResult, GradeConfiguration, ExamPerformanceAnalytics, ExamType, ExamStatus
# from src.models.previous_year_papers import PreviousYearPaper, QuestionBank, TopicPrediction, QuestionBookmark, QuestionType, DifficultyLevel, BloomTaxonomyLevel, Board
# from src.models.notification import (
#     Notification, NotificationPreference, Announcement, Message, NotificationTemplate,
#     NotificationDelivery, NotificationEngagement, NotificationAnalytics, NotificationDevice,
#     NotificationChannel, NotificationPriority, NotificationStatus, AudienceType,
#     DigestMode, NotificationGroup
# )
# from src.models.gamification import (
#     Badge, UserBadge, UserPoints, PointHistory, BadgeType, BadgeRarity, PointEventType,
#     Achievement, UserAchievement, Leaderboard, LeaderboardEntry, StreakTracker,
#     AchievementType, LeaderboardType, LeaderboardPeriod
# )
# from src.models.goal import Goal, GoalMilestone, GoalProgressLog, GoalAnalytics, GoalTemplate, GoalType, GoalStatus, MilestoneStatus
# from src.models.ml_prediction import MLModel, MLModelVersion, PerformancePrediction, PredictionScenario, ModelType, ModelStatus, PredictionType
# from src.models.study_planner import (
#     StudyPlan, WeakArea, DailyStudyTask, TopicAssignment, StudyProgress,
#     ChapterPerformance, QuestionRecommendation, FocusArea, PersonalizedInsight,
#     StudyPlanStatus, TaskStatus, TaskPriority
# )
# from src.models.analytics import (
#     AnalyticsEvent, PerformanceMetric, UserSession,
#     FeatureUsage, UserRetention
# )
# from src.models.study_material import (
#     StudyMaterial, MaterialBookmark, MaterialAccessLog, MaterialShare, MaterialTag,
#     MaterialType, ExternalContent, ExternalContentSource, ExternalContentAccessLog,
#     ContentEffectivenessScore, StudentLearningPreference
# )
# from src.models.search import SearchHistory, PopularSearch
# from src.models.fee import FeeStructure, FeePayment, FeeWaiver, FeeCategory, PaymentMethod, PaymentStatus
# from src.models.library import Book, BookCategory, BookIssue, LibrarySettings, BookStatus, IssueStatus
# from src.models.transport import TransportRoute, RouteStop, StudentTransport, RouteStatus, VehicleType
# from src.models.event import Event, EventRSVP, EventPhoto, EventType, EventStatus, RSVPStatus
# from src.models.timetable import (
#     TimetableTemplate, PeriodSlot, Timetable, TimetableEntry,
#     PeriodType
# )
# from src.models.doubt import (
#     DoubtPost, DoubtAnswer, DoubtVote, AnswerVote, DoubtBookmark, DoubtComment,
#     DoubtStatus, VoteType
# )
# from src.models.study_group import (
#     StudyGroup, GroupMember, GroupMessage, GroupResource, GroupActivity, GroupInvite,
#     StudyBuddyProfile, StudyBuddyMatch, StudySession, SessionParticipant,
#     CollaborativeNote, NoteEditor, NoteRevision, PeerTutorProfile, TutoringRequest,
#     TutoringSession, GroupPerformanceAnalytics,
#     GroupMemberRole, MessageType, ActivityType, InviteStatus, SessionStatus,
#     MatchStatus, TutorRequestStatus
# )
# from src.models.flashcard import (
#     Flashcard, FlashcardDeck, FlashcardDeckShare, FlashcardStudyProgress,
#     FlashcardStudySession, FlashcardDeckVisibility, SpacedRepetitionLevel
# )
# from src.models.quiz import (
#     Quiz, QuizQuestion, QuizAttempt, QuizResponse, QuizLeaderboard, QuizAnalytics,
#     QuizType, QuestionType, QuizStatus, QuizAttemptStatus
# )
# from src.models.ml_training import (
#     MLTrainingJob, ModelPerformanceMetrics, ModelPromotionLog,
#     TrainingStatus, TrainingJobType
# )
# from src.models.plagiarism import (
#     PlagiarismCheck, PlagiarismResult, PlagiarismMatchSegment,
#     CodeASTFingerprint, CitationPattern, PlagiarismPrivacyConsent,
#     PlagiarismCheckStatus, ComparisonScope, ContentType, ReviewDecision
# )
# from src.models.wellbeing import (
#     WellbeingAlert, AlertNote, WellbeingIntervention, SentimentAnalysis,
#     BehavioralPattern, WellbeingConsent, WellbeingDataAccess, CounselorProfile,
#     StudentWellbeingProfile, StressLevel, AlertSeverity, AlertStatus, AlertType,
#     SentimentCategory, ConsentStatus, DataAccessLevel
# )
# from src.models.conferences import (
#     ConferenceSlot, ConferenceBooking, ConferenceSurvey, ConferenceReminder,
#     LocationType, AvailabilityStatus, BookingStatus, ConferenceType
# )
# from src.models.parent_roi import ParentROIReport
# from src.models.olympics import (
#     Competition, CompetitionEvent, CompetitionEntry, CompetitionTeam,
#     CompetitionLeaderboard, CompetitionType, CompetitionScope, EventType,
#     CompetitionStatus
# )
# from src.models.career import (
#     CareerPathway, StudentCareerProfile, CareerRecommendation, SkillGapAnalysis,
#     PersonalizedLearningPath, LaborMarketData, IndustryMentor, IndustryMentorMatch,
#     CareerInterestCategory, PersonalityType, EducationLevel, IndustryType,
#     SkillLevel, RecommendationStatus, MentorshipStatus
# )
# from src.models.peer_tutoring import (
#     TutorProfile, TutoringSession, SessionParticipant, TutorReview, TutorEndorsement,
#     TutorBadge, TutorIncentive, TutorPointHistory, SessionModerationLog,
#     TutorLeaderboard, MatchingPreference,
#     TutorStatus, SessionStatus, SessionType, ReviewStatus, EndorsementType,
#     IncentiveType, BadgeCategory, ModerationActionType
# )
# from src.models.merchandise import (
#     MerchandiseItem, MerchandiseOrder, MerchandiseOrderItem, MerchandiseCommission
# )
# from src.models.onboarding import (
#     OnboardingFlow, OnboardingStep, OnboardingProgress, OnboardingStepProgress,
#     OnboardingDocument, OnboardingSignature, StepType, UserRole
# )
# from src.models.carpools import (
#     CarpoolGroup, CarpoolRequest, CarpoolRide, EmergencyNotification, CarpoolMatch,
#     CarpoolRequestType, CarpoolRequestStatus, CarpoolGroupStatus, RideStatus, EmergencyType
# )
# from src.models.journalism import (
#     NewspaperEdition, Article, ArticleReview, JournalismMember, ArticleAnalytics,
#     PublicationStatus, ArticleType, ReviewStatus, JournalismRole
# )
# from src.models.elections import (
#     Election, Candidate, Vote, VoterRegistry, ElectionResult, CampaignActivity,
#     ElectionAnalytics, ElectionPosition, EligibleVoters, ElectionStatus,
#     CandidateStatus, VoteStatus
# )
# from src.models.finance_education import (
#     FinanceLiteracyModule, ModuleCompletion, VirtualWallet, WalletTransaction,
#     InvestmentHolding, FinanceChallenge, ChallengeParticipation,
#     FinancialLiteracyAssessment, ChallengeLeaderboard,
#     ModuleName, ChallengeType, ChallengeStatus, TransactionType, InvestmentType
# )
# from src.models.entrepreneurship import (
#     StudentVenture, PitchCompetition, PitchSubmission, EntrepreneurshipMentor,
#     MentorshipRelationship, VentureFundingRequest,
#     VentureStatus, CompetitionStatus, MentorshipStatus, FundingStatus
# )
# from src.models.learning_styles import (
#     LearningStyleProfile, LearningStyleAssessment, ContentTag,
#     AdaptiveContentRecommendation, PersonalizedContentFeed, AdaptiveLearningSession,
#     LearningStyleEffectiveness, ContentDeliveryFormat, ProcessingStyle,
#     SocialPreference, AssessmentStatus
# )
# from src.models.research import (
#     ResearchProject, ResearchTeamMember, ResearchMilestone, LiteratureReference,
#     ResearchDocument, DocumentVersion, ExperimentLog, ResearchDataFile,
#     AdvisorFeedback, PeerReview, ProjectType, PublicationStatus,
#     DataCollectionStatus, MilestoneStatus, TeamMemberRole, DocumentVisibility,
#     FeedbackStatus, ReviewDecision
# )
# from src.models.study_buddy import (
#     StudyBuddySession, StudyBuddyInsight, StudyBuddyPreference, InsightType
# )
# from src.models.scholarship_essays import (
#     EssayPrompt, StudentEssay, EssayPeerReview, EssayTemplate, EssayAnalytics,
#     ReviewRubric, PromptType, EssayStatus, ReviewStatus, GrammarCheckStatus
# )
# from src.models.student_employment import (
#     StudentJobListing, WorkPermit, StudentEmployment, JobApplication,
#     JobType, PermitType, AuthorizationStatus
# )
# from src.models.mistake_analysis import (
#     MistakePattern, MistakeInsuranceToken, InsuranceReview,
#     MistakeType, RemediationStatus, EarnedVia
# )
# from src.models.reverse_classroom import (
#     TeachingSession, TeachingChallenge,
#     ExplanationType, DifficultyLevel
# )
# from src.models.subject_rpg import (
#     StudentCharacter, SubjectWorld, BattleSession, SubjectPassport, QuestLog, QuestType
# )
# from src.models.feedback import Feedback
# from src.models.school_admin import (
#     CertificateTemplate, IssuedCertificate, IDCardTemplate, StaffMember,
#     StaffPayroll, SMSTemplate, EnquiryRecord,
#     CertificateType, IssuedCertificateStatus, IDCardOrientation,
#     StaffDepartment, StaffStatus, PayrollPaymentStatus, SMSTemplateType,
#     EnquirySource, EnquiryStatus
# )

# __all__ = [
#     "Institution",
#     "User",
#     "UserSettings",
#     "UserDevice",
#     "AccountDeletionRequest",
#     "Role",
#     "Permission",
#     "Subscription",
#     "AuditLog",
#     "PasswordResetToken",
#     "AcademicYear",
#     "Grade",
#     "Section",
#     "Subject",
#     "GradeSubject",
#     "Chapter",
#     "Topic",
#     "Teacher",
#     "TeacherSubject",
#     "Student",
#     "Parent",
#     "StudentParent",
#     "Attendance",
#     "AttendanceCorrection",
#     "AttendanceSummary",
#     "AttendanceStatus",
#     "CorrectionStatus",
#     "Assignment",
#     "AssignmentFile",
#     "Submission",
#     "SubmissionFile",
#     "AssignmentStatus",
#     "SubmissionStatus",
#     "Exam",
#     "ExamSubject",
#     "ExamSchedule",
#     "ExamMarks",
#     "ExamResult",
#     "GradeConfiguration",
#     "ExamPerformanceAnalytics",
#     "ExamType",
#     "ExamStatus",
#     "PreviousYearPaper",
#     "QuestionBank",
#     "TopicPrediction",
#     "QuestionBookmark",
#     "QuestionType",
#     "DifficultyLevel",
#     "BloomTaxonomyLevel",
#     "Board",
#     "Notification",
#     "NotificationPreference",
#     "Announcement",
#     "Message",
#     "NotificationTemplate",
#     "NotificationDelivery",
#     "NotificationEngagement",
#     "NotificationAnalytics",
#     "NotificationDevice",
#     "NotificationChannel",
#     "NotificationPriority",
#     "NotificationStatus",
#     "AudienceType",
#     "DigestMode",
#     "NotificationGroup",
#     "Badge",
#     "UserBadge",
#     "UserPoints",
#     "PointHistory",
#     "BadgeType",
#     "BadgeRarity",
#     "PointEventType",
#     "Achievement",
#     "UserAchievement",
#     "Leaderboard",
#     "LeaderboardEntry",
#     "StreakTracker",
#     "AchievementType",
#     "LeaderboardType",
#     "LeaderboardPeriod",
#     "Goal",
#     "GoalMilestone",
#     "GoalProgressLog",
#     "GoalAnalytics",
#     "GoalTemplate",
#     "GoalType",
#     "GoalStatus",
#     "MilestoneStatus",
#     "MLModel",
#     "MLModelVersion",
#     "PerformancePrediction",
#     "PredictionScenario",
#     "ModelType",
#     "ModelStatus",
#     "PredictionType",
#     "StudyPlan",
#     "WeakArea",
#     "DailyStudyTask",
#     "TopicAssignment",
#     "StudyProgress",
#     "ChapterPerformance",
#     "QuestionRecommendation",
#     "FocusArea",
#     "PersonalizedInsight",
#     "StudyPlanStatus",
#     "TaskStatus",
#     "TaskPriority",
#     "AnalyticsEvent",
#     "PerformanceMetric",
#     "UserSession",
#     "FeatureUsage",
#     "UserRetention",
#     "StudyMaterial",
#     "MaterialBookmark",
#     "MaterialAccessLog",
#     "MaterialShare",
#     "MaterialTag",
#     "MaterialType",
#     "ExternalContent",
#     "ExternalContentSource",
#     "ExternalContentAccessLog",
#     "ContentEffectivenessScore",
#     "StudentLearningPreference",
#     "SearchHistory",
#     "PopularSearch",
#     "FeeStructure",
#     "FeePayment",
#     "FeeWaiver",
#     "FeeCategory",
#     "PaymentMethod",
#     "PaymentStatus",
#     "Book",
#     "BookCategory",
#     "BookIssue",
#     "LibrarySettings",
#     "BookStatus",
#     "IssueStatus",
#     "TransportRoute",
#     "RouteStop",
#     "StudentTransport",
#     "RouteStatus",
#     "VehicleType",
#     "Event",
#     "EventRSVP",
#     "EventPhoto",
#     "EventType",
#     "EventStatus",
#     "RSVPStatus",
#     "TimetableTemplate",
#     "PeriodSlot",
#     "Timetable",
#     "TimetableEntry",
#     "DayOfWeek",
#     "PeriodType",
#     "DoubtPost",
#     "DoubtAnswer",
#     "DoubtVote",
#     "AnswerVote",
#     "DoubtBookmark",
#     "DoubtComment",
#     "DoubtStatus",
#     "VoteType",
#     "StudyGroup",
#     "GroupMember",
#     "GroupMessage",
#     "GroupResource",
#     "GroupActivity",
#     "GroupInvite",
#     "StudyBuddyProfile",
#     "StudyBuddyMatch",
#     "StudySession",
#     "SessionParticipant",
#     "CollaborativeNote",
#     "NoteEditor",
#     "NoteRevision",
#     "PeerTutorProfile",
#     "TutoringRequest",
#     "TutoringSession",
#     "GroupPerformanceAnalytics",
#     "GroupMemberRole",
#     "MessageType",
#     "ActivityType",
#     "InviteStatus",
#     "SessionStatus",
#     "MatchStatus",
#     "TutorRequestStatus",
#     "Flashcard",
#     "FlashcardDeck",
#     "FlashcardDeckShare",
#     "FlashcardStudyProgress",
#     "FlashcardStudySession",
#     "FlashcardDeckVisibility",
#     "SpacedRepetitionLevel",
#     "Quiz",
#     "QuizQuestion",
#     "QuizAttempt",
#     "QuizResponse",
#     "QuizLeaderboard",
#     "QuizAnalytics",
#     "QuizType",
#     "QuestionType",
#     "QuizStatus",
#     "QuizAttemptStatus",
#     "MLTrainingJob",
#     "ModelPerformanceMetrics",
#     "ModelPromotionLog",
#     "TrainingStatus",
#     "TrainingJobType",
#     "PlagiarismCheck",
#     "PlagiarismResult",
#     "PlagiarismMatchSegment",
#     "CodeASTFingerprint",
#     "CitationPattern",
#     "PlagiarismPrivacyConsent",
#     "PlagiarismCheckStatus",
#     "ComparisonScope",
#     "ContentType",
#     "ReviewDecision",
#     "WellbeingAlert",
#     "AlertNote",
#     "WellbeingIntervention",
#     "SentimentAnalysis",
#     "BehavioralPattern",
#     "WellbeingConsent",
#     "WellbeingDataAccess",
#     "CounselorProfile",
#     "StudentWellbeingProfile",
#     "StressLevel",
#     "AlertSeverity",
#     "AlertStatus",
#     "AlertType",
#     "SentimentCategory",
#     "ConsentStatus",
#     "DataAccessLevel",
#     "ConferenceSlot",
#     "ConferenceBooking",
#     "ConferenceSurvey",
#     "ConferenceReminder",
#     "LocationType",
#     "AvailabilityStatus",
#     "BookingStatus",
#     "ConferenceType",
#     "ParentROIReport",
#     "Competition",
#     "CompetitionEvent",
#     "CompetitionEntry",
#     "CompetitionTeam",
#     "CompetitionLeaderboard",
#     "CompetitionType",
#     "CompetitionScope",
#     "EventType",
#     "CompetitionStatus",
#     "CareerPathway",
#     "StudentCareerProfile",
#     "CareerRecommendation",
#     "SkillGapAnalysis",
#     "PersonalizedLearningPath",
#     "LaborMarketData",
#     "IndustryMentor",
#     "IndustryMentorMatch",
#     "CareerInterestCategory",
#     "PersonalityType",
#     "EducationLevel",
#     "IndustryType",
#     "SkillLevel",
#     "RecommendationStatus",
#     "MentorshipStatus",
#     "TutorProfile",
#     "TutoringSession",
#     "SessionParticipant",
#     "TutorReview",
#     "TutorEndorsement",
#     "TutorBadge",
#     "TutorIncentive",
#     "TutorPointHistory",
#     "SessionModerationLog",
#     "TutorLeaderboard",
#     "MatchingPreference",
#     "TutorStatus",
#     "SessionStatus",
#     "SessionType",
#     "ReviewStatus",
#     "EndorsementType",
#     "IncentiveType",
#     "BadgeCategory",
#     "ModerationActionType",
#     "MerchandiseItem",
#     "MerchandiseOrder",
#     "MerchandiseOrderItem",
#     "MerchandiseCommission",
#     "OnboardingFlow",
#     "OnboardingStep",
#     "OnboardingProgress",
#     "OnboardingStepProgress",
#     "OnboardingDocument",
#     "OnboardingSignature",
#     "StepType",
#     "UserRole",
#     "CarpoolGroup",
#     "CarpoolRequest",
#     "CarpoolRide",
#     "EmergencyNotification",
#     "CarpoolMatch",
#     "CarpoolRequestType",
#     "CarpoolRequestStatus",
#     "CarpoolGroupStatus",
#     "RideStatus",
#     "EmergencyType",
#     "NewspaperEdition",
#     "Article",
#     "ArticleReview",
#     "JournalismMember",
#     "ArticleAnalytics",
#     "PublicationStatus",
#     "ArticleType",
#     "ReviewStatus",
#     "JournalismRole",
#     "Election",
#     "Candidate",
#     "Vote",
#     "VoterRegistry",
#     "ElectionResult",
#     "CampaignActivity",
#     "ElectionAnalytics",
#     "ElectionPosition",
#     "EligibleVoters",
#     "ElectionStatus",
#     "CandidateStatus",
#     "VoteStatus",
#     "FinanceLiteracyModule",
#     "ModuleCompletion",
#     "VirtualWallet",
#     "WalletTransaction",
#     "InvestmentHolding",
#     "FinanceChallenge",
#     "ChallengeParticipation",
#     "FinancialLiteracyAssessment",
#     "ChallengeLeaderboard",
#     "ModuleName",
#     "ChallengeType",
#     "ChallengeStatus",
#     "TransactionType",
#     "InvestmentType",
#     "StudentVenture",
#     "PitchCompetition",
#     "PitchSubmission",
#     "EntrepreneurshipMentor",
#     "MentorshipRelationship",
#     "VentureFundingRequest",
#     "VentureStatus",
#     "CompetitionStatus",
#     "MentorshipStatus",
#     "FundingStatus",
#     "LearningStyleProfile",
#     "LearningStyleAssessment",
#     "ContentTag",
#     "AdaptiveContentRecommendation",
#     "PersonalizedContentFeed",
#     "AdaptiveLearningSession",
#     "LearningStyleEffectiveness",
#     "ContentDeliveryFormat",
#     "ProcessingStyle",
#     "SocialPreference",
#     "AssessmentStatus",
#     "ResearchProject",
#     "ResearchTeamMember",
#     "ResearchMilestone",
#     "LiteratureReference",
#     "ResearchDocument",
#     "DocumentVersion",
#     "ExperimentLog",
#     "ResearchDataFile",
#     "AdvisorFeedback",
#     "PeerReview",
#     "ProjectType",
#     "PublicationStatus",
#     "DataCollectionStatus",
#     "MilestoneStatus",
#     "TeamMemberRole",
#     "DocumentVisibility",
#     "FeedbackStatus",
#     "ReviewDecision",
#     "StudyBuddySession",
#     "StudyBuddyInsight",
#     "StudyBuddyPreference",
#     "InsightType",
#     "EssayPrompt",
#     "StudentEssay",
#     "EssayPeerReview",
#     "EssayTemplate",
#     "EssayAnalytics",
#     "ReviewRubric",
#     "PromptType",
#     "EssayStatus",
#     "ReviewStatus",
#     "GrammarCheckStatus",
#     "StudentJobListing",
#     "WorkPermit",
#     "StudentEmployment",
#     "JobApplication",
#     "JobType",
#     "PermitType",
#     "AuthorizationStatus",
#     "MistakePattern",
#     "MistakeInsuranceToken",
#     "InsuranceReview",
#     "MistakeType",
#     "RemediationStatus",
#     "EarnedVia",
#     "TeachingSession",
#     "TeachingChallenge",
#     "ExplanationType",
#     "DifficultyLevel",
#     "StudentCharacter",
#     "SubjectWorld",
#     "BattleSession",
#     "SubjectPassport",
#     "QuestLog",
#     "QuestType",
#     "Feedback",
#     "CertificateTemplate",
#     "IssuedCertificate",
#     "IDCardTemplate",
#     "StaffMember",
#     "StaffPayroll",
#     "SMSTemplate",
#     "EnquiryRecord",
#     "CertificateType",
#     "IssuedCertificateStatus",
#     "IDCardOrientation",
#     "StaffDepartment",
#     "StaffStatus",
#     "PayrollPaymentStatus",
#     "SMSTemplateType",
#     "EnquirySource",
#     "EnquiryStatus",
# ]

from src.models.institution import Institution
from src.models.user import User
from src.models.user_settings import UserSettings, UserDevice, AccountDeletionRequest
from src.models.role import Role
from src.models.permission import Permission
from src.models.subscription import Subscription
from src.models.audit_log import AuditLog
from src.models.password_reset_token import PasswordResetToken
from src.models.academic import AcademicYear, Grade, Section, Subject, GradeSubject, Chapter, Topic, DayOfWeek
from src.models.teacher import Teacher, TeacherSubject
from src.models.student import Student, Parent, StudentParent
from src.models.attendance import Attendance, AttendanceCorrection, AttendanceSummary, AttendanceStatus, CorrectionStatus
from src.models.assignment import Assignment, AssignmentFile, Submission, SubmissionFile, AssignmentStatus, SubmissionStatus
from src.models.examination import Exam, ExamSubject, ExamSchedule, ExamMarks, ExamResult, GradeConfiguration, ExamPerformanceAnalytics, ExamType, ExamStatus
from src.models.previous_year_papers import PreviousYearPaper, QuestionBank, TopicPrediction, QuestionBookmark, QuestionType, DifficultyLevel, BloomTaxonomyLevel, Board
from src.models.notification import (
    Notification, NotificationPreference, Announcement, Message, NotificationTemplate,
    NotificationDelivery, NotificationEngagement, NotificationAnalytics, NotificationDevice,
    NotificationChannel, NotificationPriority, NotificationStatus, AudienceType,
    DigestMode, NotificationGroup
)
from src.models.gamification import (
    Badge, UserBadge, UserPoints, PointHistory, BadgeType, BadgeRarity, PointEventType,
    Achievement, UserAchievement, Leaderboard, LeaderboardEntry, StreakTracker,
    AchievementType, LeaderboardType, LeaderboardPeriod
)
from src.models.goal import Goal, GoalMilestone, GoalProgressLog, GoalAnalytics, GoalTemplate, GoalType, GoalStatus, MilestoneStatus
from src.models.ml_prediction import MLModel, MLModelVersion, PerformancePrediction, PredictionScenario, ModelType, ModelStatus, PredictionType
from src.models.study_planner import (
    StudyPlan, WeakArea, DailyStudyTask, TopicAssignment, StudyProgress,
    ChapterPerformance, QuestionRecommendation, FocusArea, PersonalizedInsight,
    StudyPlanStatus, TaskStatus, TaskPriority
)
from src.models.analytics import (
    AnalyticsEvent, PerformanceMetric, UserSession,
    FeatureUsage, UserRetention
)
from src.models.study_material import (
    StudyMaterial, MaterialBookmark, MaterialAccessLog, MaterialShare, MaterialTag,
    MaterialType, ExternalContent, ExternalContentSource, ExternalContentAccessLog,
    ContentEffectivenessScore, StudentLearningPreference
)
from src.models.search import SearchHistory, PopularSearch
from src.models.fee import FeeStructure, FeePayment, FeeWaiver, FeeCategory, PaymentMethod, PaymentStatus
from src.models.library import Book, BookCategory, BookIssue, LibrarySettings, BookStatus, IssueStatus
from src.models.transport import TransportRoute, RouteStop, StudentTransport, RouteStatus, VehicleType
from src.models.event import Event, EventRSVP, EventPhoto, EventType, EventStatus, RSVPStatus
from src.models.timetable import (
    TimetableTemplate, PeriodSlot, Timetable, TimetableEntry,
    PeriodType
)
from src.models.doubt import (
    DoubtPost, DoubtAnswer, DoubtVote, AnswerVote, DoubtBookmark, DoubtComment,
    DoubtStatus, VoteType
)
from src.models.study_group import (
    StudyGroup, GroupMember, GroupMessage, GroupResource, GroupActivity, GroupInvite,
    StudyBuddyProfile, StudyBuddyMatch, StudySession, SessionParticipant,
    CollaborativeNote, NoteEditor, NoteRevision, PeerTutorProfile, TutoringRequest,
    TutoringSession, GroupPerformanceAnalytics,
    GroupMemberRole, MessageType, ActivityType, InviteStatus, SessionStatus,
    MatchStatus, TutorRequestStatus
)
from src.models.flashcard import (
    Flashcard, FlashcardDeck, FlashcardDeckShare, FlashcardStudyProgress,
    FlashcardStudySession, FlashcardDeckVisibility, SpacedRepetitionLevel
)
from src.models.quiz import (
    Quiz, QuizQuestion, QuizAttempt, QuizResponse, QuizLeaderboard, QuizAnalytics,
    QuizType, QuestionType, QuizStatus, QuizAttemptStatus
)

# ❌ COMMENTED OUT - CAUSING ERROR
# Reason: File `src/models/ml_training.py` does NOT exist in project
# So importing it crashes the application
# Uncomment this ONLY when you create ml_training module

# from src.models.ml_training import (
#     MLTrainingJob, ModelPerformanceMetrics, ModelPromotionLog,
#     TrainingStatus, TrainingJobType
# )

from src.models.plagiarism import (
    PlagiarismCheck, PlagiarismResult, PlagiarismMatchSegment,
    CodeASTFingerprint, CitationPattern, PlagiarismPrivacyConsent,
    PlagiarismCheckStatus, ComparisonScope, ContentType, ReviewDecision
)

from src.models.wellbeing import (
    WellbeingAlert, AlertNote, WellbeingIntervention, SentimentAnalysis,
    BehavioralPattern, WellbeingConsent, WellbeingDataAccess, CounselorProfile,
    StudentWellbeingProfile, StressLevel, AlertSeverity, AlertStatus, AlertType,
    SentimentCategory, ConsentStatus, DataAccessLevel
)

from src.models.feedback import Feedback
from src.models.school_admin import (
    CertificateTemplate, IssuedCertificate, IDCardTemplate, StaffMember,
    StaffPayroll, SMSTemplate, EnquiryRecord,
    CertificateType, IssuedCertificateStatus, IDCardOrientation,
    StaffDepartment, StaffStatus, PayrollPaymentStatus, SMSTemplateType,
    EnquirySource, EnquiryStatus
)

__all__ = [
    "Institution",
    "User",
    "UserSettings",
    "UserDevice",
    "AccountDeletionRequest",
    "Role",
    "Permission",
    "Subscription",
    "AuditLog",
    "PasswordResetToken",
    "AcademicYear",
    "Grade",
    "Section",
    "Subject",
    "GradeSubject",
    "Chapter",
    "Topic",
    "Teacher",
    "TeacherSubject",
    "Student",
    "Parent",
    "StudentParent",
    "Attendance",
    "AttendanceCorrection",
    "AttendanceSummary",
    "AttendanceStatus",
    "CorrectionStatus",
    "Assignment",
    "AssignmentFile",
    "Submission",
    "SubmissionFile",
    "AssignmentStatus",
    "SubmissionStatus",
    "Exam",
    "ExamSubject",
    "ExamSchedule",
    "ExamMarks",
    "ExamResult",
    "GradeConfiguration",
    "ExamPerformanceAnalytics",
    "ExamType",
    "ExamStatus",
    "PreviousYearPaper",
    "QuestionBank",
    "TopicPrediction",
    "QuestionBookmark",
    "QuestionType",
    "DifficultyLevel",
    "BloomTaxonomyLevel",
    "Board",
    "Notification",
    "NotificationPreference",
    "Announcement",
    "Message",
    "NotificationTemplate",
    "NotificationDelivery",
    "NotificationEngagement",
    "NotificationAnalytics",
    "NotificationDevice",
    "NotificationChannel",
    "NotificationPriority",
    "NotificationStatus",
    "AudienceType",
    "DigestMode",
    "NotificationGroup",
    "Badge",
    "UserBadge",
    "UserPoints",
    "PointHistory",
    "BadgeType",
    "BadgeRarity",
    "PointEventType",
    "Achievement",
    "UserAchievement",
    "Leaderboard",
    "LeaderboardEntry",
    "StreakTracker",
    "AchievementType",
    "LeaderboardType",
    "LeaderboardPeriod",
    "Goal",
    "GoalMilestone",
    "GoalProgressLog",
    "GoalAnalytics",
    "GoalTemplate",
    "GoalType",
    "GoalStatus",
    "MilestoneStatus",
    "MLModel",
    "MLModelVersion",
    "PerformancePrediction",
    "PredictionScenario",
    "ModelType",
    "ModelStatus",
    "PredictionType",
    "StudyPlan",
    "WeakArea",
    "DailyStudyTask",
    "TopicAssignment",
    "StudyProgress",
    "ChapterPerformance",
    "QuestionRecommendation",
    "FocusArea",
    "PersonalizedInsight",
    "StudyPlanStatus",
    "TaskStatus",
    "TaskPriority",
    "AnalyticsEvent",
    "PerformanceMetric",
    "UserSession",
    "FeatureUsage",
    "UserRetention",
    "StudyMaterial",
    "MaterialBookmark",
    "MaterialAccessLog",
    "MaterialShare",
    "MaterialTag",
    "MaterialType",
    "ExternalContent",
    "ExternalContentSource",
    "ExternalContentAccessLog",
    "ContentEffectivenessScore",
    "StudentLearningPreference",
    "SearchHistory",
    "PopularSearch",
    "FeeStructure",
    "FeePayment",
    "FeeWaiver",
    "FeeCategory",
    "PaymentMethod",
    "PaymentStatus",
    "Book",
    "BookCategory",
    "BookIssue",
    "LibrarySettings",
    "BookStatus",
    "IssueStatus",
    "TransportRoute",
    "RouteStop",
    "StudentTransport",
    "RouteStatus",
    "VehicleType",
    "Event",
    "EventRSVP",
    "EventPhoto",
    "EventType",
    "EventStatus",
    "RSVPStatus",
    "TimetableTemplate",
    "PeriodSlot",
    "Timetable",
    "TimetableEntry",
    "DayOfWeek",
    "PeriodType",
    "DoubtPost",
    "DoubtAnswer",
    "DoubtVote",
    "AnswerVote",
    "DoubtBookmark",
    "DoubtComment",
    "DoubtStatus",
    "VoteType",
    "StudyGroup",
    "GroupMember",
    "GroupMessage",
    "GroupResource",
    "GroupActivity",
    "GroupInvite",
    "StudyBuddyProfile",
    "StudyBuddyMatch",
    "StudySession",
    "SessionParticipant",
    "CollaborativeNote",
    "NoteEditor",
    "NoteRevision",
    "PeerTutorProfile",
    "TutoringRequest",
    "TutoringSession",
    "GroupPerformanceAnalytics",
    "GroupMemberRole",
    "MessageType",
    "ActivityType",
    "InviteStatus",
    "SessionStatus",
    "MatchStatus",
    "TutorRequestStatus",
    "Flashcard",
    "FlashcardDeck",
    "FlashcardDeckShare",
    "FlashcardStudyProgress",
    "FlashcardStudySession",
    "FlashcardDeckVisibility",
    "SpacedRepetitionLevel",
    "Quiz",
    "QuizQuestion",
    "QuizAttempt",
    "QuizResponse",
    "QuizLeaderboard",
    "QuizAnalytics",
    "QuizType",
    "QuestionType",
    "QuizStatus",
    "QuizAttemptStatus",
    "MLTrainingJob",
    "ModelPerformanceMetrics",
    "ModelPromotionLog",
    "TrainingStatus",
    "TrainingJobType",
    "PlagiarismCheck",
    "PlagiarismResult",
    "PlagiarismMatchSegment",
    "CodeASTFingerprint",
    "CitationPattern",
    "PlagiarismPrivacyConsent",
    "PlagiarismCheckStatus",
    "ComparisonScope",
    "ContentType",
    "ReviewDecision",
    "WellbeingAlert",
    "AlertNote",
    "WellbeingIntervention",
    "SentimentAnalysis",
    "BehavioralPattern",
    "WellbeingConsent",
    "WellbeingDataAccess",
    "CounselorProfile",
    "StudentWellbeingProfile",
    "StressLevel",
    "AlertSeverity",
    "AlertStatus",
    "AlertType",
    "SentimentCategory",
    "ConsentStatus",
    "DataAccessLevel",
    "ConferenceSlot",
    "ConferenceBooking",
    "ConferenceSurvey",
    "ConferenceReminder",
    "LocationType",
    "AvailabilityStatus",
    "BookingStatus",
    "ConferenceType",
    "ParentROIReport",
    "Competition",
    "CompetitionEvent",
    "CompetitionEntry",
    "CompetitionTeam",
    "CompetitionLeaderboard",
    "CompetitionType",
    "CompetitionScope",
    "EventType",
    "CompetitionStatus",
    "CareerPathway",
    "StudentCareerProfile",
    "CareerRecommendation",
    "SkillGapAnalysis",
    "PersonalizedLearningPath",
    "LaborMarketData",
    "IndustryMentor",
    "IndustryMentorMatch",
    "CareerInterestCategory",
    "PersonalityType",
    "EducationLevel",
    "IndustryType",
    "SkillLevel",
    "RecommendationStatus",
    "MentorshipStatus",
    "TutorProfile",
    "TutoringSession",
    "SessionParticipant",
    "TutorReview",
    "TutorEndorsement",
    "TutorBadge",
    "TutorIncentive",
    "TutorPointHistory",
    "SessionModerationLog",
    "TutorLeaderboard",
    "MatchingPreference",
    "TutorStatus",
    "SessionStatus",
    "SessionType",
    "ReviewStatus",
    "EndorsementType",
    "IncentiveType",
    "BadgeCategory",
    "ModerationActionType",
    "MerchandiseItem",
    "MerchandiseOrder",
    "MerchandiseOrderItem",
    "MerchandiseCommission",
    "OnboardingFlow",
    "OnboardingStep",
    "OnboardingProgress",
    "OnboardingStepProgress",
    "OnboardingDocument",
    "OnboardingSignature",
    "StepType",
    "UserRole",
    "CarpoolGroup",
    "CarpoolRequest",
    "CarpoolRide",
    "EmergencyNotification",
    "CarpoolMatch",
    "CarpoolRequestType",
    "CarpoolRequestStatus",
    "CarpoolGroupStatus",
    "RideStatus",
    "EmergencyType",
    "NewspaperEdition",
    "Article",
    "ArticleReview",
    "JournalismMember",
    "ArticleAnalytics",
    "PublicationStatus",
    "ArticleType",
    "ReviewStatus",
    "JournalismRole",
    "Election",
    "Candidate",
    "Vote",
    "VoterRegistry",
    "ElectionResult",
    "CampaignActivity",
    "ElectionAnalytics",
    "ElectionPosition",
    "EligibleVoters",
    "ElectionStatus",
    "CandidateStatus",
    "VoteStatus",
    "FinanceLiteracyModule",
    "ModuleCompletion",
    "VirtualWallet",
    "WalletTransaction",
    "InvestmentHolding",
    "FinanceChallenge",
    "ChallengeParticipation",
    "FinancialLiteracyAssessment",
    "ChallengeLeaderboard",
    "ModuleName",
    "ChallengeType",
    "ChallengeStatus",
    "TransactionType",
    "InvestmentType",
    "StudentVenture",
    "PitchCompetition",
    "PitchSubmission",
    "EntrepreneurshipMentor",
    "MentorshipRelationship",
    "VentureFundingRequest",
    "VentureStatus",
    "CompetitionStatus",
    "MentorshipStatus",
    "FundingStatus",
    "LearningStyleProfile",
    "LearningStyleAssessment",
    "ContentTag",
    "AdaptiveContentRecommendation",
    "PersonalizedContentFeed",
    "AdaptiveLearningSession",
    "LearningStyleEffectiveness",
    "ContentDeliveryFormat",
    "ProcessingStyle",
    "SocialPreference",
    "AssessmentStatus",
    "ResearchProject",
    "ResearchTeamMember",
    "ResearchMilestone",
    "LiteratureReference",
    "ResearchDocument",
    "DocumentVersion",
    "ExperimentLog",
    "ResearchDataFile",
    "AdvisorFeedback",
    "PeerReview",
    "ProjectType",
    "PublicationStatus",
    "DataCollectionStatus",
    "MilestoneStatus",
    "TeamMemberRole",
    "DocumentVisibility",
    "FeedbackStatus",
    "ReviewDecision",
    "StudyBuddySession",
    "StudyBuddyInsight",
    "StudyBuddyPreference",
    "InsightType",
    "EssayPrompt",
    "StudentEssay",
    "EssayPeerReview",
    "EssayTemplate",
    "EssayAnalytics",
    "ReviewRubric",
    "PromptType",
    "EssayStatus",
    "ReviewStatus",
    "GrammarCheckStatus",
    "StudentJobListing",
    "WorkPermit",
    "StudentEmployment",
    "JobApplication",
    "JobType",
    "PermitType",
    "AuthorizationStatus",
    "MistakePattern",
    "MistakeInsuranceToken",
    "InsuranceReview",
    "MistakeType",
    "RemediationStatus",
    "EarnedVia",
    "TeachingSession",
    "TeachingChallenge",
    "ExplanationType",
    "DifficultyLevel",
    "StudentCharacter",
    "SubjectWorld",
    "BattleSession",
    "SubjectPassport",
    "QuestLog",
    "QuestType",
    "Feedback",
    "CertificateTemplate",
    "IssuedCertificate",
    "IDCardTemplate",
    "StaffMember",
    "StaffPayroll",
    "SMSTemplate",
    "EnquiryRecord",
    "CertificateType",
    "IssuedCertificateStatus",
    "IDCardOrientation",
    "StaffDepartment",
    "StaffStatus",
    "PayrollPaymentStatus",
    "SMSTemplateType",
    "EnquirySource",
    "EnquiryStatus",
]
